import type { Album } from "./types";

/**
 * Punk / alternatif rock keşif albümleri (1980'lerden bugüne).
 * 70'ler bilerek yok: atalar 80'ler post-punk ve 90'lar grunge/alt-rock.
 */
export const discoveryAlbums: Album[] = [
  {
    slug: "staind-break-the-cycle",
    artist: "Staind",
    title: "Break the Cycle",
    year: 2001,
    deezerId: 339259,
    genres: ["Post-grunge", "Alternatif metal"],
    origin: "Springfield, Massachusetts, ABD",
    why: "Three Days Grace ve Breaking Benjamin'in en yakın kuzenlerinden: \"It's Been Awhile\" ve \"Fade\".",
    story: [
      "Aaron Lewis'in kırık, neredeyse konuşur gibi vokali 2000'lerin rock radyosunu ele geçirdi. Break the Cycle, grubun ikinci albümü ve Limp Bizkit'in Fred Durst'unun keşfettiği bir New England grubunun ana akıma çıkışı.",
      "\"It's Been Awhile\" Hot 100'de Top 5'e girdi — o dönem bir post-grunge şarkısı için nadir bir pop başarısı. Albüm ABD'de 8 milyona yakın sattı; \"Fade\", \"For You\" ve \"Outside\" (Family Values'daki akustik versiyonuyla) grubun imzası oldu.",
    ],
    artistInfo:
      "Staind: Aaron Lewis (vokal), Mike Mushok (gitar), Johnny April (bas) ve Jon Wysocki (davul). Lewis sonradan country'ye kaydı; bu albüm grubun rock kimliğinin zirvesi.",
    members: ["Aaron Lewis – vokal", "Mike Mushok – gitar", "Johnny April – bas", "Jon Wysocki – davul"],
    funFacts: [
      "\"Outside\" önce Family Values turnesinde akustik olarak patladı; stüdyo versiyonu sonradan kaydedildi.",
      "Albüm Billboard 200'e 1 numaradan girdi.",
      "Lewis, sahnede oturarak şarkı söylemesiyle 2000'lerin rock görsel dilinin bir parçası oldu.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "disturbed-the-sickness",
    artist: "Disturbed",
    title: "The Sickness",
    year: 2000,
    deezerId: 344758,
    genres: ["Nu metal", "Alternatif metal"],
    origin: "Chicago, Illinois, ABD",
    why: "\"Down with the Sickness\" — Three Days Grace'in öfkesini nu metal'in en büyük çıkış albümünde duyarsın.",
    story: [
      "Chicago'lu dörtlünün çıkış albümü, David Draiman'ın staccato vokali ve o ünlü 'oh-ah-ah-ah' nidasıyla bir kuşağın spor salonu marşı oldu. \"Down with the Sickness\", \"Stupify\" ve \"Voices\" albümü platinin ötesine taşıdı.",
      "Sözler zihinsel hastalık, istismar ve öfke üzerine kurulu; kapaktaki kırmızı figür Disturbed'un kalıcı görseli haline geldi. Albüm yayımlanmasından yıllar sonra bile rock radyosunun temel taşlarından biri.",
    ],
    artistInfo:
      "Disturbed: David Draiman (vokal), Dan Donegan (gitar), Steve Kmak (bas, bu albümde) ve Mike Wengren (davul). Grup sonraki albümlerinde daha melodik bir heavy metal'e evrildi.",
    members: ["David Draiman – vokal", "Dan Donegan – gitar", "Steve Kmak – bas", "Mike Wengren – davul"],
    funFacts: [
      "\"Down with the Sickness\"deki nida, Draiman'ın stüdyoda doğaçlama çıkardığı bir sestı.",
      "Albüm ABD'de 5 kez platin sertifika aldı.",
      "Grup adı, Draiman'ın 'rahatsız edici' şarkı sözlerine bir gönderme.",
    ],
    relatedTo: ["Three Days Grace"],
  },
  {
    slug: "godsmack-faceless",
    artist: "Godsmack",
    title: "Faceless",
    year: 2003,
    deezerId: 15734168,
    genres: ["Alternatif metal", "Hard rock"],
    origin: "Lawrence, Massachusetts, ABD",
    why: "Sully Erna'nın shaman davulları ve \"I Stand Alone\" — post-grunge'ın daha karanlık, daha ağır yüzü.",
    story: [
      "Faceless, Godsmack'in Billboard 200'e 1 numaradan giren ilk albümü. \"I Stand Alone\" The Scorpion King fragmanında kullanıldı ve albüm çıkmadan radyo hiti oldu.",
      "\"Straight Out of Line\" ve \"Serenity\" ile grup hem ağır riffleri hem akustik tarafını gösterdi. Sully Erna'nın Native American perküsyon tutkusu, konserlerdeki davul düellosunun temelini attı.",
    ],
    artistInfo:
      "Godsmack, Sully Erna'nın 1995'te Alice in Chains'e selam veren bir isimle kurduğu grup. Faceless kadrosu: Erna, Tony Rombola, Robbie Merrill ve Shannon Larkin.",
    members: ["Sully Erna – vokal, ritim gitar", "Tony Rombola – solo gitar", "Robbie Merrill – bas", "Shannon Larkin – davul"],
    funFacts: [
      "Grup adı Alice in Chains'in \"God Smack\" şarkısından geliyor.",
      "\"I Stand Alone\", The Scorpion King için yazıldı ve sonra albüme alındı.",
      "Shannon Larkin bu albümle gruba katıldı; önceki davulcu Tommy Stewart'tı.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "afi-sing-the-sorrow",
    artist: "AFI",
    title: "Sing the Sorrow",
    year: 2003,
    deezerId: 8929593,
    genres: ["Alternatif rock", "Emo", "Post-hardcore"],
    origin: "Ukiah, Kaliforniya, ABD",
    why: "Hardcore'dan gothic pop'a yürüyen bir grubun \"Girl's Not Grey\" ve \"Silver and Cold\" albümü.",
    story: [
      "AFI yıllarca yeraltı hardcore sahnelerinde çaldı; Sing the Sorrow ile Butch Vig ve Jerry Finn prodüksiyonunda ana akıma çıktı. Davey Havok'un teatral vokali, Panic! ve MCR'ın birkaç yıl sonra dolduracağı alanı önceden işaret etti.",
      "Albüm Billboard 200'e 5 numaradan girdi. \"Girl's Not Grey\" Modern Rock'ta zirveye yürüdü; kapanıştaki \"This Celluloid Dream\" gothic atmosferin zirvesi.",
    ],
    artistInfo:
      "AFI (A Fire Inside): Davey Havok (vokal), Jade Puget (gitar), Hunter Burgan (bas) ve Adam Carson (davul). Havok ve Carson liseden beri birlikte.",
    members: ["Davey Havok – vokal", "Jade Puget – gitar", "Hunter Burgan – bas", "Adam Carson – davul"],
    funFacts: [
      "Butch Vig (Nevermind, Siamese Dream) ve Jerry Finn (Blink-182) birlikte prodüksiyon yaptı.",
      "\"Death of Seasons\"teki çocuk korosu, albümün en ürkütücü anlarından biri.",
      "Havok, AFI'nin yanında gothic rock projesi Blaqk Audio'yu da yürüttü.",
    ],
    relatedTo: ["Panic! At the Disco", "My Chemical Romance"],
  },
  {
    slug: "the-used-in-love-and-death",
    artist: "The Used",
    title: "In Love and Death",
    year: 2004,
    deezerId: 340916,
    genres: ["Emo", "Post-hardcore", "Alternatif rock"],
    origin: "Orem, Utah, ABD",
    why: "Bert McCracken'ın çığlığı ve \"Take It Away\" — Panic! öncesi emo'nun en ham kaydı.",
    story: [
      "İkinci albüm, Bert McCracken'ın o dönemki kız arkadaşının hamilelikte kaybı ve yakın bir arkadaşın ölümü üzerine yazıldı; albüm adı tam olarak bunu söylüyor. Jerry Finn prodüksiyonu, çığlıkları pop nakaratların yanına koydu.",
      "\"Take It Away\", \"All That I've Got\" ve \"I Caught Fire\" emo radyosunun 2004'ünü tanımladı. My Chemical Romance ile yapılan \"Under Pressure\" cover'ı da bu döneme denk gelir.",
    ],
    artistInfo:
      "The Used: Bert McCracken (vokal), Quinn Allman (gitar), Jeph Howard (bas) ve Branden Steineckert (davul, bu albümde). Grup Utah'ın Mormon coğrafyasından çıkıp Warped Tour'un yüzü oldu.",
    members: ["Bert McCracken – vokal", "Quinn Allman – gitar", "Jeph Howard – bas", "Branden Steineckert – davul"],
    funFacts: [
      "McCracken, albüm kaydı sırasında evsiz kalacak kadar dağınık bir dönemden geçti.",
      "\"Hard to Say\" kaybedilen bebek için yazıldı.",
      "Steineckert albümden sonra Rancid'e geçti.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "thrice-the-artist-in-the-ambulance",
    artist: "Thrice",
    title: "The Artist in the Ambulance",
    year: 2003,
    deezerId: 246442,
    genres: ["Post-hardcore", "Alternatif rock"],
    origin: "Irvine, Kaliforniya, ABD",
    why: "Zeki, ağır ve melodik: Breaking Benjamin'in düşünceli kuzeni.",
    story: [
      "Albüm adı, 'sanatçı ambulansın içinde' metaforuyla sanatı acil bir müdahale gibi görme fikrine dayanıyor. \"Stare at the Sun\" ve \"All That's Left\" Warped Tour kitlesini Island Records ölçeğine taşıdı.",
      "Dustin Kensrue'nun sözleri politik ve kişisel arasında gidip gelir; grup bu albümden sonra deneysel Vheissu'ya yönelecekti. Artist in the Ambulance, Thrice'ın en 'erişilebilir' ve en çok dinlenen kaydı olarak kaldı.",
    ],
    artistInfo:
      "Thrice: Dustin Kensrue (vokal, gitar), Teppei Teranishi (gitar), Eddie Breckenridge (bas) ve Riley Breckenridge (davul). Kardeşler Breckenridge kadronun sabit omurgası.",
    members: ["Dustin Kensrue – vokal, gitar", "Teppei Teranishi – gitar, klavye", "Eddie Breckenridge – bas", "Riley Breckenridge – davul"],
    funFacts: [
      "Albüm satışlarının bir kısmı bir tıp yardım kuruluşuna bağışlandı — isimle uyumlu bir jest.",
      "\"Stare at the Sun\" grubun ilk büyük radyo hiti oldu.",
      "Grup 2012'de ara verip 2016'da To Be Everywhere Is to Be Nowhere ile döndü.",
    ],
    relatedTo: ["Breaking Benjamin", "Panic! At the Disco"],
  },
  {
    slug: "taking-back-sunday-tell-all-your-friends",
    artist: "Taking Back Sunday",
    title: "Tell All Your Friends",
    year: 2002,
    deezerId: 113017822,
    genres: ["Emo", "Pop punk", "Alternatif rock"],
    origin: "Amityville, New York, ABD",
    why: "Çift vokal, sahne kavgası ve \"Cute Without the 'E'\" — 2000'ler emo'sunun kurucu kaydı.",
    story: [
      "Long Island'dan çıkan grup, Adam Lazzara ve John Nolan'ın iç içe geçen vokalleriyle emo'ya yeni bir sahne dili getirdi. \"Cute Without the 'E' (Cut from the Team)\" ve \"You're So Last Summer\" bir kuşağın kırık kalp marşları oldu.",
      "Albüm bağımsız Victory Records'tan çıktı ve kelimenin tam anlamıyla kulaktan kulağa yayıldı. Nolan albümden kısa süre sonra gruptan ayrılıp Straylight Run'ı kurdu; yıllar sonra geri döndü.",
    ],
    artistInfo:
      "Taking Back Sunday'in bu kadrosu: Adam Lazzara (vokal), John Nolan (gitar, vokal), Eddie Reyes (gitar), Shaun Cooper (bas) ve Mark O'Connell (davul).",
    members: ["Adam Lazzara – vokal", "John Nolan – gitar, vokal", "Eddie Reyes – gitar", "Shaun Cooper – bas", "Mark O'Connell – davul"],
    funFacts: [
      "Lazzara sahnede mikrofonu kabloyla savurmasıyla ünlü; bu hareket bu albümün turnesinde doğdu.",
      "\"There's No 'I' in Team\" şarkısı, grubun kendi iç gerilimini de anlatır.",
      "Albüm başlığı, dedikodu ve ihanet temalarının kısa bir özeti.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "brand-new-deja-entendu",
    artist: "Brand New",
    title: "Deja Entendu",
    year: 2003,
    deezerId: 320972327,
    genres: ["Emo", "Alternatif rock", "Indie rock"],
    origin: "Merrick, New York, ABD",
    why: "Long Island emo'sunun en edebi albümü; Panic!'in söz takıntısına akraba.",
    story: [
      "Çıkış albümleri Your Favorite Weapon pop-punk'tı; Deja Entendu ile Jesse Lacey daha karanlık, daha yetişkin bir ses yazdı. \"The Quiet Things That No One Ever Knows\" ve \"Sic Transit Gloria... Glory Fades\" klipleriyle MTV2'nin yüzü oldular.",
      "Albüm adı Fransızca 'zaten duyulmuş' anlamına geliyor — bir déjà vu şakası. Sonraki The Devil and God Are Raging Inside Me daha da karanlık olacaktı; bu kayıt o geçişin eşiği.",
    ],
    artistInfo:
      "Brand New: Jesse Lacey (vokal, gitar), Vincent Accardi (gitar), Garrett Tierney (bas) ve Brian Lane (davul). Grup 2010'ların sonunda sahneyi bıraktı.",
    members: ["Jesse Lacey – vokal, gitar", "Vincent Accardi – gitar", "Garrett Tierney – bas", "Brian Lane – davul"],
    funFacts: [
      "\"Sic Transit Gloria\" klibi bir lise partisinin tek mekânda çekilmiş kaotik bir anlatısı.",
      "Taking Back Sunday ile Long Island sahnesinde hem dost hem rakip olarak anıldılar.",
      "Albüm, birçok eleştirmene göre 2000'ler emo'sunun en iyi ikinci albüm geçişi.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "jimmy-eat-world-bleed-american",
    artist: "Jimmy Eat World",
    title: "Bleed American",
    year: 2001,
    deezerId: 85606432,
    genres: ["Alternatif rock", "Emo pop", "Power pop"],
    origin: "Mesa, Arizona, ABD",
    why: "\"The Middle\" — emo'nun radyoya gülümsediği an; Panic! ve Paramore'un yolunu açtı.",
    story: [
      "Capitol'ün grubu kovmasından sonra kendi imkânlarıyla kaydettikleri albüm, 11 Eylül'den sonra isim yüzünden geçici olarak Jimmy Eat World adıyla yeniden basıldı. \"The Middle\", Jim Adkins'in bir hayran mektubuna yanıt olarak yazdığı bir cesaret şarkısı.",
      "\"Sweetness\", \"A Praise Chorus\" ve başlık parçası, Arizona'lı dörtlüyü Warped Tour'dan stadyum ön grupluğuna taşıdı. Temiz prodüksiyon ve umutlu nakaratlar, emo'nun 'gülümseyen' yüzünü tanımladı.",
    ],
    artistInfo:
      "Jimmy Eat World: Jim Adkins (vokal, gitar), Tom Linton (gitar), Rick Burch (bas) ve Zach Lind (davul). Grup 1993'ten beri aynı çekirdekle ayakta.",
    members: ["Jim Adkins – vokal, gitar", "Tom Linton – gitar, vokal", "Rick Burch – bas", "Zach Lind – davul"],
    funFacts: [
      "\"The Middle\", Adkins'in 'her şey yoluna girecek' demek istediği kısa bir nottan büyüdü.",
      "Albüm 11 Eylül sonrası bazı basımlarda sadece grup adıyla satıldı.",
      "Clarity (1999) kült bir öncül olsa da ticari kapıyı bu albüm açtı.",
    ],
    relatedTo: ["Panic! At the Disco", "Imagine Dragons"],
  },
  {
    slug: "blink-182-enema-of-the-state",
    artist: "Blink-182",
    title: "Enema of the State",
    year: 1999,
    deezerId: 102409042,
    genres: ["Pop punk"],
    origin: "Poway, Kaliforniya, ABD",
    why: "Pop-punk'ın pop'a dönüştüğü albüm; Panic! ve Fall Out Boy'un çocukluk kaseti.",
    story: [
      "Jerry Finn prodüksiyonundaki üçüncü albüm, hem kaba mizahı hem \"Adam's Song\"daki depresyonu aynı plağa koydu. \"All the Small Things\" klibi boy band parodisi olarak MTV'yi ele geçirdi; \"What's My Age Again?\" çıplak koşusuyla sansür tartışması yarattı.",
      "Travis Barker'ın davula katıldığı ilk stüdyo albümü. 15 milyondan fazla satarak pop-punk'ı 2000'lerin ana akımına taşıdı — Green Day Dookie'den sonraki büyük patlama.",
    ],
    artistInfo:
      "blink-182: Tom DeLonge (gitar, vokal), Mark Hoppus (bas, vokal) ve Travis Barker (davul). Hem çocukça hem ölümcül ciddi olabilen ender bir grup.",
    members: ["Tom DeLonge – gitar, vokal", "Mark Hoppus – bas, vokal", "Travis Barker – davul"],
    funFacts: [
      "Kapaktaki hemşire pornografik film oyuncusu Janine Lindemulder; kapak bazı mağazalarda sticker ile kapatıldı.",
      "\"Adam's Song\", bir hayranın intihar notundan ve Hoppus'un tur yorgunluğundan doğdu.",
      "Barker, The Aquabats'ten transfer oldu.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "yellowcard-ocean-avenue",
    artist: "Yellowcard",
    title: "Ocean Avenue",
    year: 2003,
    deezerId: 319831,
    genres: ["Pop punk", "Alternatif rock"],
    origin: "Jacksonville, Florida, ABD",
    why: "Kemanlı pop-punk: \"Ocean Avenue\" hâlâ yaz bitmeyen bir kaliforniya rüyası gibi.",
    story: [
      "Florida'lı grubun kemancı Sean Mackin'i kadroya alması onları Warped Tour kalabalığından ayırdı. Başlık şarkısı bir sokağın nostaljisi; klibi kaykay, yaz ve 2003 MTV'si demek.",
      "\"Only One\" ve \"Way Away\" ile albüm platin oldu. Shinedown ile aynı Jacksonville sahnesinden çıkan Yellowcard, pop-punk'ın en melodik yüzünü temsil etti.",
    ],
    artistInfo:
      "Yellowcard: Ryan Key (vokal, gitar), Sean Mackin (keman, vokal), Ben Harper (gitar, bu albümde), Pete Mosely (bas) ve Longineu Parsons III (davul).",
    members: ["Ryan Key – vokal, gitar", "Sean Mackin – keman, vokal", "Ben Harper – gitar", "Pete Mosely – bas", "Longineu Parsons III – davul"],
    funFacts: [
      "Keman, pop-punk'ta neredeyse hiç duyulmayan bir ana enstrümandı; Mackin sahnede zıplayarak çalıyor.",
      "\"Ocean Avenue\" gerçek bir sokak: grup üyelerinin takıldığı bir cadde.",
      "Grup 2016'da vedalaşıp 2020'lerde yeniden turneye çıktı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "all-time-low-so-wrong-its-right",
    artist: "All Time Low",
    title: "So Wrong, It's Right",
    year: 2007,
    deezerId: 571749,
    genres: ["Pop punk", "Emo pop"],
    origin: "Towson, Maryland, ABD",
    why: "\"Dear Maria, Count Me In\" — Panic! ile aynı Fueled by Ramen kuşağının sahne şarkısı.",
    story: [
      "Lise yıllarında kurulan Maryland'li dörtlünün ikinci albümü, Hopeless Records'tan çıkan bir pop-punk patlaması. \"Dear Maria, Count Me In\" bir striptiz kulübü şarkısı olarak yazıldı ve grubun sonsuz kapanış parçası oldu.",
      "Alex Gaskarth'ın alaycı sözleri ve Jack Barakat'ın sahne soytarılığı, 2007 Warped Tour'unun yüzüydü. Albüm, All Time Low'u bir internet grubundan arena ön grubuna taşıdı.",
    ],
    artistInfo:
      "All Time Low: Alex Gaskarth (vokal, gitar), Jack Barakat (gitar), Zack Merrick (bas) ve Rian Dawson (davul). İsim, New Found Glory şarkısından geliyor.",
    members: ["Alex Gaskarth – vokal, gitar", "Jack Barakat – gitar, vokal", "Zack Merrick – bas", "Rian Dawson – davul"],
    funFacts: [
      "\"Dear Maria, Count Me In\" klibi bir ev partisinde çekildi ve düşük bütçeli haliyle viral oldu.",
      "Grup üyeleri albüm çıktığında 19-21 yaşındaydı.",
      "Fueled by Ramen ile değil Hopeless ile çıkmaları, onları Panic!'in etiket komşusu değil sahne arkadaşı yaptı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "pierce-the-veil-collide-with-the-sky",
    artist: "Pierce the Veil",
    title: "Collide with the Sky",
    year: 2012,
    deezerId: 12752604,
    genres: ["Post-hardcore", "Emo", "Alternatif rock"],
    origin: "San Diego, Kaliforniya, ABD",
    why: "Vic Fuentes'in falsettosu ve \"King for a Day\" — sahne emo'sunun 2010'lardaki zirvesi.",
    story: [
      "Kellogg kardeşlerin (Vic ve Mike Fuentes) grubu üçüncü albümünde Fearless Records ile stadyum nakaratları yazdı. \"King for a Day\"de Kellin Quinn (Sleeping With Sirens) konuk; şarkı bir kuşak TikTok'tan önce bile sahnelerin kapanış parçasıydı.",
      "\"Bulls in the Bronx\" gerçek bir haberden, bir gencin ölümü üzerine yazıldı. Albüm, sahne emo'sunu (scene) Warped Tour'un son büyük dalgasında tuttu.",
    ],
    artistInfo:
      "Pierce the Veil: Vic Fuentes (vokal, gitar), Mike Fuentes (davul), Tony Perry (gitar) ve Jaime Preciado (bas). Meksika asıllı bir San Diego grubu.",
    members: ["Vic Fuentes – vokal, gitar", "Tony Perry – gitar", "Jaime Preciado – bas, vokal", "Mike Fuentes – davul"],
    funFacts: [
      "\"King for a Day\" hâlâ grubun en çok dinlenen şarkısı.",
      "Albüm kapağındaki uçan kız, 'gökyüzüyle çarpışma' metaforunun görseli.",
      "Vic ve Mike Fuentes kardeş; evde yazılan şarkılar stüdyoya neredeyse hazır geliyordu.",
    ],
    relatedTo: ["Panic! At the Disco", "The Pretty Reckless"],
  },
  {
    slug: "sleeping-with-sirens-feel",
    artist: "Sleeping With Sirens",
    title: "Feel",
    year: 2013,
    deezerId: 889022982,
    genres: ["Post-hardcore", "Alternatif rock", "Emo pop"],
    origin: "Orlando, Florida, ABD",
    why: "Kellin Quinn'in tiz vokali: Pretty Reckless'in teatral enerjisini sahne emo'sunda arıyorsan.",
    story: [
      "Feel, grubun daha radyo dostu, daha pop bir albümü. \"Low\" ve \"Alone\" (MGK ile) Warped Tour'dan Mainstream Rock listesine uzanan bir köprü kurdu.",
      "Quinn'in beş oktava yaklaşan tizleri, 2010'ların sahne vokalistlerinin ölçütü oldu. Albüm, post-hardcore'u One Direction dinleyen bir kitleye de açtı — kimileri bunu ihanet, kimileri evrim saydı.",
    ],
    artistInfo:
      "Sleeping With Sirens: Kellin Quinn (vokal), Jack Fowler ve Nick Martin (gitar), Justin Hills (bas) ve Gabe Barham (davul, bu albümde).",
    members: ["Kellin Quinn – vokal, klavye", "Jack Fowler – gitar", "Nick Martin – gitar", "Justin Hills – bas", "Gabe Barham – davul"],
    funFacts: [
      "Quinn, Pierce the Veil'in \"King for a Day\"ında konuk vokal yaptığı için iki grup sıkça birlikte anılır.",
      "Albüm Billboard 200'e 3 numaradan girdi.",
      "\"Alone\"daki MGK düeti, emo ve rap'in 2010'lardaki erken kesişimlerinden.",
    ],
    relatedTo: ["Panic! At the Disco", "The Pretty Reckless"],
  },
  {
    slug: "the-offspring-smash",
    artist: "The Offspring",
    title: "Smash",
    year: 1994,
    deezerId: 43852191,
    genres: ["Punk rock", "Pop punk"],
    origin: "Garden Grove, Kaliforniya, ABD",
    why: "Bağımsız bir etiketten çıkan en çok satan albümlerden; Green Day Dookie ile aynı yazın diğer kutbu.",
    story: [
      "Epitaph Records'tan çıkan Smash, \"Come Out and Play\", \"Self Esteem\" ve \"Gotta Get Away\" ile 90'lar punk revival'ının ticari kanıtı oldu. Dexter Holland'ın 'keep 'em separated' nakaratı bir yazın sloganıydı.",
      "Albüm 11 milyondan fazla satarak bağımsız bir punk plağı için rekor kırdı. Kaliforniya skate punk'ı, Nirvana sonrası Amerika'nın diğer büyük alternatif kapısı oldu.",
    ],
    artistInfo:
      "The Offspring: Dexter Holland (vokal, gitar), Noodles (gitar), Greg K. (bas) ve Ron Welty (davul, bu albümde). Holland aynı zamanda bir moleküler biyoloji doktorasına sahip.",
    members: ["Dexter Holland – vokal, gitar", "Noodles – gitar", "Greg K. – bas", "Ron Welty – davul"],
    funFacts: [
      "\"Come Out and Play\"deki 'keep 'em separated', bir lise kavgası haberinden çıktı.",
      "Smash, bağımsız bir etiket albümü olarak onlarca yıl satmaya devam etti.",
      "Grup Orange County skate sahnesinden geliyor; konserlerde hâlâ sörf-punk enerjisi var.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "green-day-dookie",
    artist: "Green Day",
    title: "Dookie",
    year: 1994,
    deezerId: 81912,
    genres: ["Punk rock", "Pop punk"],
    origin: "Berkeley, Kaliforniya, ABD",
    why: "American Idiot'tan on yıl önce: punk'ı MTV'ye taşıyan albüm.",
    story: [
      "Lookout! günlerinden Reprise'a geçen üçlü, Rob Cavallo ile 19 günde Dookie'yi kaydetti. \"Basket Case\", \"Longview\", \"When I Come Around\" ve \"Welcome to Paradise\" 1994'ü yeşil saçlı bir punk yazına çevirdi.",
      "Albüm 20 milyondan fazla sattı ve Grammy kazandı. Berkeley'deki 924 Gilman Street sahnesinin bir kısmı 'satış' diye sırt çevirdi; geri kalan dünya Green Day'i öğrendi.",
    ],
    artistInfo:
      "Green Day: Billie Joe Armstrong, Mike Dirnt ve Tré Cool. Dookie, Tré Cool'un tam oturduğu ve grubun stadyuma giden yolu açtığı kayıttır.",
    members: ["Billie Joe Armstrong – vokal, gitar", "Mike Dirnt – bas, vokal", "Tré Cool – davul"],
    funFacts: [
      "\"Basket Case\" Armstrong'un panik ataklarıyla ilgili; klip bir akıl hastanesinde geçer.",
      "Kapaktaki köpek dışkısı, albüm adına (dookie = kaka) birebir gönderme.",
      "\"Longview\" Dirnt'in evde sıkıntıdan yazdığı bir bas hattıyla başladı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "weezer-blue-album",
    artist: "Weezer",
    title: "Weezer (Blue Album)",
    year: 1994,
    deezerId: 249099,
    genres: ["Alternatif rock", "Power pop", "Pop punk"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "Ric Ocasek prodüksiyonlu nerd-rock: The Neighbourhood ve Panic!'in melodi aşkının 90'lardaki hali.",
    story: [
      "Cars'ın Ric Ocasek'i, Rivers Cuomo'nun dört gözlü, riff'li pop şarkılarını parlatmak için seçildi. \"Buddy Holly\", Spike Jonze'un Happy Days klibiyle MTV'yi yıktı; \"Say It Ain't So\" bir babanın alkolizmi üzerine.",
      "Albüm, grunge'ın yanında duran neşeli, utangaç bir alternatif yüz oldu. Cuomo kısa süre sonra Harvard'a gitti; Pinkerton daha karanlık gelecekti.",
    ],
    artistInfo:
      "Weezer: Rivers Cuomo (vokal, gitar), Brian Bell (gitar), Matt Sharp (bas, bu albümde) ve Patrick Wilson (davul). Grup adını Cuomo'nun babasının lakabından aldı.",
    members: ["Rivers Cuomo – vokal, gitar", "Brian Bell – gitar, vokal", "Matt Sharp – bas, vokal", "Patrick Wilson – davul"],
    funFacts: [
      "\"Buddy Holly\" klibi Happy Days görüntüleriyle birleştirildi; Paramount ilk başta izin vermek istemedi.",
      "Cuomo, albümden sonra bacak ameliyatı geçirdi ve bir süre bastonla gezdi.",
      "Kapaktaki mavi, Cars'ın ilk albüm kapağına bir selam.",
    ],
    relatedTo: ["Panic! At the Disco", "The Neighbourhood"],
  },
  {
    slug: "pixies-doolittle",
    artist: "Pixies",
    title: "Doolittle",
    year: 1989,
    deezerId: 106387,
    genres: ["Alternatif rock", "Bağımsız rock"],
    origin: "Boston, Massachusetts, ABD",
    why: "Sakin-patlama şablonu: Nirvana, Radiohead ve The Neighbourhood'un ortak büyükannesi.",
    story: [
      "Gil Norton prodüksiyonundaki Doolittle, Black Francis'in İncil, sürrealizm ve uzaylı hikâyelerini iki dakikalık şarkılara sıkıştırdı. \"Debaser\", \"Here Comes Your Man\", \"Monkey Gone to Heaven\" ve \"Hey\" alternatif rock'ın DNA'sı oldu.",
      "Kurt Cobain, Nevermind'ı yazarken Doolittle'ı açıkça çaldığını söyledi. Kim Deal'ın bas hatları ve \"Gigantic\"teki vokali, grubun ikinci motoru.",
    ],
    artistInfo:
      "Pixies: Black Francis (vokal, gitar), Kim Deal (bas, vokal), Joey Santiago (gitar) ve David Lovering (davul). 1989'da henüz yeraltıydılar; etkisi 90'larda patladı.",
    members: ["Black Francis – vokal, gitar", "Kim Deal – bas, vokal", "Joey Santiago – gitar", "David Lovering – davul"],
    funFacts: [
      "\"Debaser\", Buñuel'in Un Chien Andalou filmine gönderme — 'slicin' up eyeballs'.",
      "Cobain, Pixies'i 'çaldığım riff'lerin kaynağı' olarak gösterdi.",
      "Albüm adı, bir bıçak cinayeti haberindeki 'doolittle' kelimesinden geliyor.",
    ],
    relatedTo: ["The Neighbourhood", "The Beatles"],
  },
  {
    slug: "the-cure-disintegration",
    artist: "The Cure",
    title: "Disintegration",
    year: 1989,
    deezerId: 1347457,
    genres: ["Alternatif rock", "Gothic rock", "New wave"],
    origin: "Crawley, İngiltere",
    why: "Karanlık pop'un kutsal kitabı; The Neighbourhood'un gece paletinin atası.",
    story: [
      "Robert Smith 30 yaşına girerken 'son büyük albüm' diye yola çıktı; plak şirketi şarkıları çok uzun ve çok yavaş buldu. \"Pictures of You\", \"Lovesong\", \"Fascination Street\" ve \"Plainsong\" gotik atmosferi stadyuma taşıdı.",
      "\"Lovesong\"u Smith eşine düğün hediyesi olarak yazdı ve şarkı ABD'de Top 5'e girdi. Disintegration, The Cure'un hem en kişisel hem en başarılı kaydı sayılır.",
    ],
    artistInfo:
      "The Cure, Robert Smith'in 1978'den beri yönettiği grup. Bu kadroda Porl Thompson, Simon Gallup, Boris Williams ve Roger O'Donnell var.",
    members: ["Robert Smith – vokal, gitar", "Simon Gallup – bas", "Porl Thompson – gitar", "Boris Williams – davul", "Roger O'Donnell – klavye"],
    funFacts: [
      "Smith, şirketin albümü 'ticari değil' bulmasına rağmen hiçbir şarkıyı kısaltmayı reddetti.",
      "\"Lovesong\", Mary Poole ile evliliğinin hediyesi.",
      "Kapaktaki doku, Smith'in çocukken etkilendiği orman ve yağmur imgelerinden geliyor.",
    ],
    relatedTo: ["The Neighbourhood"],
  },
  {
    slug: "the-smiths-the-queen-is-dead",
    artist: "The Smiths",
    title: "The Queen Is Dead",
    year: 1986,
    deezerId: 1261474,
    genres: ["Alternatif rock", "Bağımsız rock", "Jangle pop"],
    origin: "Manchester, İngiltere",
    why: "Morrissey'nin alayı ve Johnny Marr'ın gitarı — bağımsız rock'ın anayasası; Broken Bells'in melodisinin büyükbabası.",
    story: [
      "1986 İngiltere'sinin Thatcher dönemine bir ayna: \"The Queen Is Dead\", \"There Is a Light That Never Goes Out\" ve \"Bigmouth Strikes Again\". Marr'ın açık akortları ve Morrissey'nin edebi alayı, sonraki 30 yılın indie gruplarının şablonu oldu.",
      "Albüm, Smiths'in dağılmasından bir yıl önce geldi. Britpop (Oasis, Blur) ve 2000'ler indie'si (The Strokes hariç neredeyse herkes) bu plağı kutsal saydı.",
    ],
    artistInfo:
      "The Smiths: Morrissey (vokal), Johnny Marr (gitar), Andy Rourke (bas) ve Mike Joyce (davul). Dört yıl, dört stüdyo albümü, sonra hukuki bir dağılış.",
    members: ["Morrissey – vokal", "Johnny Marr – gitar", "Andy Rourke – bas", "Mike Joyce – davul"],
    funFacts: [
      "\"There Is a Light That Never Goes Out\" o dönemde single bile olmadı; sonradan grubun imzası sayıldı.",
      "Kapak, 1960'ların Alain Delon filminden bir kare.",
      "Marr, bazı şarkılarda 10'dan fazla gitar katmanı kullandı.",
    ],
    relatedTo: ["Broken Bells", "The Beatles"],
  },
  {
    slug: "new-order-power-corruption-and-lies",
    artist: "New Order",
    title: "Power, Corruption & Lies",
    year: 1983,
    deezerId: 11253936,
    genres: ["New wave", "Synth-pop", "Alternatif"],
    origin: "Manchester, İngiltere",
    why: "Joy Division'ın küllerinden dans müziği: The Killers ve The Neighbourhood'un elektronik damarının kaynağı.",
    story: [
      "Ian Curtis'in ölümünden sonra kalan üçlü, Gillian Gilbert'ı alıp post-punk'ı sequencer'a bağladı. \"Age of Consent\" ve \"Your Silent Face\" hâlâ soğuk, hâlâ dans edilebilir.",
      "Albümde \"Blue Monday\" yok (ayrı single'dı) ama aynı dönemin ruhu burada. Peter Saville'ın çiçek kodlu kapağı, Factory Records tasarımının ikonlarından.",
    ],
    artistInfo:
      "New Order: Bernard Sumner (vokal, gitar), Peter Hook (bas), Stephen Morris (davul) ve Gillian Gilbert (klavye). Joy Division'ın devamı, ama başka bir türün kurucusu.",
    members: ["Bernard Sumner – vokal, gitar", "Peter Hook – bas", "Stephen Morris – davul", "Gillian Gilbert – klavye"],
    funFacts: [
      "Kapaktaki renk kodu albüm adını ve katalog numarasını şifreliyor.",
      "\"Blue Monday\", bu albümle aynı dönemde kaydedildi ama 12\" single olarak ayrı basıldı.",
      "The Killers'ın adı, New Order'ın \"Crystal\" klibindeki sahte bir gruptan geliyor.",
    ],
    relatedTo: ["Imagine Dragons", "The Neighbourhood"],
  },
  {
    slug: "radiohead-the-bends",
    artist: "Radiohead",
    title: "The Bends",
    year: 1995,
    deezerId: 14880317,
    genres: ["Alternatif rock", "Britpop"],
    origin: "Abingdon, İngiltere",
    why: "\"Fake Plastic Trees\" ve \"High and Dry\" — Imagine Dragons'ın stadyum hüznünün İngiliz atası.",
    story: [
      "\"Creep\"in tek hit grubu olmaktan korkan Radiohead, John Leckie ile gitar katmanlarını ve Thom Yorke'un falsettosunu öne çıkardı. \"Just\", \"Street Spirit (Fade Out)\" ve \"Fake Plastic Trees\" Britpop'un gölgesinde duran daha karanlık bir İngiltere çizdi.",
      "The Bends, OK Computer'dan önceki son 'klasik gitar albümü'. Birçok grup (Muse dahil) bu plağı çalarak büyüdü.",
    ],
    artistInfo:
      "Radiohead: Thom Yorke, Jonny Greenwood, Colin Greenwood, Ed O'Brien ve Philip Selway. Okul arkadaşlarından oluşan beşli, Oxfordshire'dan çıkıp 90'ların en önemli İngiliz grubu oldu.",
    members: ["Thom Yorke – vokal, gitar", "Jonny Greenwood – gitar, klavye", "Ed O'Brien – gitar, vokal", "Colin Greenwood – bas", "Philip Selway – davul"],
    funFacts: [
      "\"Fake Plastic Trees\" Yorke'un tek bir duygusal take'inde kaydedildi; sonrasında ağladığı anlatılır.",
      "Albüm adı, dalgıçların ani çıkışta yaşadığı basınç hastalığı — ani şöhretin metaforu.",
      "\"Street Spirit\" klibi, Yorke'un en sevdiği görsellerinden biri olmaya devam etti.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "radiohead-ok-computer",
    artist: "Radiohead",
    title: "OK Computer",
    year: 1997,
    deezerId: 14879699,
    genres: ["Alternatif rock", "Art rock"],
    origin: "Abingdon, İngiltere",
    why: "Teknoloji kaygısının rock operası; Muse ve Imagine Dragons'ın stadyum hırsının ölçütü.",
    story: [
      "Bir malikânede kaydedilen OK Computer, Paranoid Android'in üç bölümlü yapısı, \"Karma Police\" ve \"No Surprises\" ile 90'ların sonunu tanımladı. Yorke, milenyum öncesi yorgunluk ve makineleşme üzerine yazdı.",
      "Albüm Grammy'de En İyi Alternatif Albüm aldı ve sık sık 'tüm zamanların en iyileri' listelerinin tepesine konur. Sonraki Kid A elektronik bir kopuş olacaktı; bu plak hâlâ gitarın albümü.",
    ],
    artistInfo:
      "Nigel Godrich'in prodüksiyonu grubun 'altıncı üyesi' sayılır. OK Computer, Radiohead'i Britpop'tan koparıp sanat-rock ligine koydu.",
    members: ["Thom Yorke – vokal, gitar", "Jonny Greenwood – gitar, ondes Martenot", "Ed O'Brien – gitar", "Colin Greenwood – bas", "Philip Selway – davul"],
    funFacts: [
      "\"Paranoid Android\" Queen'in \"Bohemian Rhapsody\"sine bir selam olarak üç parçaya bölündü.",
      "\"No Surprises\"deki çocuksu zil sesi, karanlık sözlerle bilinçli bir kontrast.",
      "Yorke, albüm dönemi röportajlarında uçak korkusu ve tanıtım turu tükenmişliğini sıkça anlatır.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "smashing-pumpkins-siamese-dream",
    artist: "The Smashing Pumpkins",
    title: "Siamese Dream",
    year: 1993,
    deezerId: 1452137,
    genres: ["Alternatif rock", "Grunge", "Shoegaze"],
    origin: "Chicago, Illinois, ABD",
    why: "Butch Vig'in duvar gitarları: Breaking Benjamin'in katmanlı sesinin 90'lardaki anıtı.",
    story: [
      "Billy Corgan albümün neredeyse tüm gitar ve bas partilerini kendisi çaldı; James Iha ve D'arcy gerilimli bir dönemdeydi, Jimmy Chamberlin ise bağımlılıkla boğuşuyordu. Butch Vig (Nevermind) bu kaosu \"Today\", \"Disarm\" ve \"Cherub Rock\"a çevirdi.",
      "Corgan'ın mükemmeliyetçiliği kayıtları kabusa çevirdi ama sonuç, 90'lar alternatifinin en dolgun gitar albümlerinden biri oldu. \"Mayonaise\" hayranların kutsal parçası.",
    ],
    artistInfo:
      "Smashing Pumpkins: Billy Corgan (vokal, gitar), James Iha (gitar), D'arcy Wretzky (bas) ve Jimmy Chamberlin (davul). Corgan, Breaking Benjamin'in We Are Not Alone'una da şarkı yazmıştı.",
    members: ["Billy Corgan – vokal, gitar, bas", "James Iha – gitar", "D'arcy Wretzky – bas", "Jimmy Chamberlin – davul"],
    funFacts: [
      "Corgan bazı şarkılarda 40'tan fazla gitar katmanı kullandı.",
      "\"Today\" neşeli bir riff'in altına intihar düşüncelerini gizler.",
      "Corgan, Breaking Benjamin ile 2004'te üç şarkı yazdı — bu yüzden iki grup kütüphanende yan yana duruyor.",
    ],
    relatedTo: ["Breaking Benjamin"],
  },
  {
    slug: "pearl-jam-ten",
    artist: "Pearl Jam",
    title: "Ten",
    year: 1991,
    deezerId: 708674,
    genres: ["Grunge", "Alternatif rock"],
    origin: "Seattle, Washington, ABD",
    why: "Eddie Vedder'ın baritonu: post-grunge vokalistlerin (Gontier, Burnley, Morgan) ortak atası.",
    story: [
      "Mother Love Bone'un Andrew Wood'un ölümünden sonra Stone Gossard ve Jeff Ament, San Diego'dan bir kaset gönderen Eddie Vedder'ı kadroya aldı. Ten, \"Alive\", \"Even Flow\" ve \"Jeremy\" ile Nevermind'ın yanındaki diğer Seattle depremi oldu.",
      "Albüm yavaş başladı, sonra yıllarca listelerde kaldı. Vedder'ın sahne duruşu — gözler kapalı, mikrofon sehpasına asılı — 90'lar rock'ının duruşu haline geldi.",
    ],
    artistInfo:
      "Pearl Jam: Eddie Vedder, Stone Gossard, Mike McCready, Jeff Ament ve Dave Krusen (bu albümde davul). Grup, Nirvana ile birlikte grunge'ı dünyaya duyurdu ama daha uzun yaşadı.",
    members: ["Eddie Vedder – vokal, gitar", "Stone Gossard – ritim gitar", "Mike McCready – solo gitar", "Jeff Ament – bas", "Dave Krusen – davul"],
    funFacts: [
      "Vedder sözleri, Gossard'ın enstrümantal demoları üzerine bir sörf gezisinde yazdı.",
      "\"Jeremy\", bir sınıf içinde silahlı bir öğrencinin gerçek haberinden yola çıkar.",
      "Albüm adı, basketbolcu Mookie Blaylock'un formasının numarası; ilk grup adı da Mookie Blaylock'tı.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "alice-in-chains-dirt",
    artist: "Alice in Chains",
    title: "Dirt",
    year: 1992,
    deezerId: 1399089,
    genres: ["Grunge", "Alternatif metal"],
    origin: "Seattle, Washington, ABD",
    why: "Layne Staley ve Jerry Cantrell'in uyumlu vokalleri: Breaking Benjamin'in koro armonilerinin karanlık kaynağı.",
    story: [
      "Dirt, bağımlılığın içinden yazılmış bir albüm. \"Them Bones\", \"Would?\", \"Rooster\" ve \"Down in a Hole\" hem ağır hem acı derecede melodik. Dave Jerden prodüksiyonu, gitarları boğuk ve vokal armonilerini öne çıkardı.",
      "\"Rooster\", Cantrell'in Vietnam'daki babası hakkında; \"Would?\" ise Andrew Wood'un anısına. Staley 2002'de hayata veda etti; Cantrell grubu yıllar sonra William DuVall ile sürdürdü.",
    ],
    artistInfo:
      "Alice in Chains: Layne Staley (vokal), Jerry Cantrell (gitar, vokal), Mike Starr (bas, bu albümde) ve Sean Kinney (davul). Seattle'ın en metal'e yakın grunge grubu.",
    members: ["Layne Staley – vokal", "Jerry Cantrell – gitar, vokal", "Mike Starr – bas", "Sean Kinney – davul"],
    funFacts: [
      "Cantrell ve Staley'nin ikili armonileri, metal ve grunge'ı birbirine bağlayan en net köprü.",
      "\"Would?\" Singles film soundtrack'inde de yer aldı.",
      "Godsmack'in adı, Alice in Chains'in \"God Smack\" şarkısından gelir.",
    ],
    relatedTo: ["Breaking Benjamin", "Three Days Grace"],
  },
  {
    slug: "soundgarden-superunknown",
    artist: "Soundgarden",
    title: "Superunknown",
    year: 1994,
    deezerId: 7816775,
    genres: ["Grunge", "Alternatif metal", "Hard rock"],
    origin: "Seattle, Washington, ABD",
    why: "Chris Cornell'in dört oktavı: Pretty Reckless'in Cornell sevgisinin kaynağı ve 90'ların en büyük rock albümlerinden.",
    story: [
      "Michael Beinhorn prodüksiyonundaki Superunknown, \"Black Hole Sun\", \"Spoonman\", \"Fell on Black Days\" ve \"The Day I Tried to Live\" ile Soundgarden'ı stadyuma taşıdı. Cornell'in vokali Zeppelin'den punk'a uzanan bir köprüydü.",
      "Albüm Billboard 200'e 1 numaradan girdi. \"Black Hole Sun\" klibinin suburban distopyası, 90'ların en hatırlanan görsellerinden. The Pretty Reckless yıllar sonra Soundgarden'ın açılış grubu oldu; Cornell'in ölümü Death by Rock and Roll'un yasının bir parçası.",
    ],
    artistInfo:
      "Soundgarden: Chris Cornell, Kim Thayil, Ben Shepherd ve Matt Cameron. Cameron aynı zamanda Pearl Jam'in davulcusu oldu.",
    members: ["Chris Cornell – vokal, gitar", "Kim Thayil – gitar", "Ben Shepherd – bas", "Matt Cameron – davul"],
    funFacts: [
      "\"Spoonman\", Seattle sokak müzisyeni Artis the Spoonman üzerine; gerçek kaşık sesleri kayıtta var.",
      "Kim Thayil ve Matt Cameron, Pretty Reckless'in \"Only Love Can Save Me Now\"ında çaldı.",
      "Albüm adı Cornell'in bir yazım hatasından doğdu: 'unknown' üstüne 'super'.",
    ],
    relatedTo: ["The Pretty Reckless"],
  },
  {
    slug: "deftones-white-pony",
    artist: "Deftones",
    title: "White Pony",
    year: 2000,
    deezerId: 97368,
    genres: ["Alternatif metal", "Shoegaze", "Nu metal"],
    origin: "Sacramento, Kaliforniya, ABD",
    why: "Nu metal'in en şairane albümü; Neighbourhood'un karanlığıyla Breaking Benjamin'in ağırlığını birleştirir.",
    story: [
      "White Pony ile Deftones nu metal etiketini geride bırakıp rüya gibi, erotik ve ağır bir ses kurdu. \"Change (In the House of Flies)\", \"Digital Bath\" ve \"Passenger\" (Maynard James Keenan ile) 2000'lerin en etkili rock kayıtlarından.",
      "Chino Moreno'nun fısıltıdan çığlığa geçişi, Frank Delgado'nun turntable/sample katmanları ve Terry Date prodüksiyonu, albümü hem metal hem indie dinleyicisine açtı.",
    ],
    artistInfo:
      "Deftones: Chino Moreno, Stephen Carpenter, Chi Cheng (bas, bu albümde), Abe Cunningham ve Frank Delgado. Sacramento'lu çocukluk arkadaşları.",
    members: ["Chino Moreno – vokal, gitar", "Stephen Carpenter – gitar", "Chi Cheng – bas", "Abe Cunningham – davul", "Frank Delgado – klavye, sample"],
    funFacts: [
      "Albüm adı, hem kokain hem de rüya atı imgelerine gönderme.",
      "\"Passenger\"daki Maynard (Tool) vokali, stüdyoda tek bir gecede doğdu.",
      "White Pony, Grammy'de En İyi Metal Performansı ödülünü \"Elite\" ile kazandı.",
    ],
    relatedTo: ["Breaking Benjamin", "The Neighbourhood"],
  },
  {
    slug: "system-of-a-down-toxicity",
    artist: "System of a Down",
    title: "Toxicity",
    year: 2001,
    deezerId: 1434890,
    genres: ["Alternatif metal", "Nu metal"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "Garip, politik ve nakaratlı: Panic!'in teatralliğiyle Three Days Grace'in ağırlığını tek grupta.",
    story: [
      "Rick Rubin prodüksiyonundaki Toxicity, 11 Eylül haftasında yayımlanmasına rağmen \"Chop Suey!\", \"Toxicity\" ve \"Aerials\" ile dünya çapında patladı. Serj Tankian'ın opera-rap vokali ve Daron Malakian'ın riff'leri Ermeni asıllı bir L.A. grubunu stadyuma taşıdı.",
      "Sözler savaş, hapishane, gıda endüstrisi ve delilik arasında zıplar. Albüm Billboard 200'e 1 numaradan girdi.",
    ],
    artistInfo:
      "System of a Down: Serj Tankian (vokal), Daron Malakian (gitar, vokal), Shavo Odadjian (bas) ve John Dolmayan (davul). Dört üye de Ermeni kökenli.",
    members: ["Serj Tankian – vokal, klavye", "Daron Malakian – gitar, vokal", "Shavo Odadjian – bas", "John Dolmayan – davul"],
    funFacts: [
      "\"Chop Suey!\"in orijinal adı \"Suicide\"dı; radyo için bölündü.",
      "Albüm 11 Eylül'den bir hafta önce çıktı; \"Chop Suey!\" klibindeki uçak görüntüleri bazı kanallarda kesildi.",
      "Grup uzun yıllar yeni albüm yayımlamadan sadece turne yaptı.",
    ],
    relatedTo: ["Three Days Grace", "Panic! At the Disco"],
  },
  {
    slug: "incubus-make-yourself",
    artist: "Incubus",
    title: "Make Yourself",
    year: 1999,
    deezerId: 1372048,
    genres: ["Alternatif rock", "Alternatif metal"],
    origin: "Calabasas, Kaliforniya, ABD",
    why: "\"Drive\" ve \"Pardon Me\": nu metal'den melodik alt-rock'a geçen, Imagine Dragons öncesi Kaliforniya.",
    story: [
      "Funk-metal çıkışlı Incubus, Make Yourself ile DJ Kilmore'u kadroda tutup şarkıları radyo dostu hale getirdi. \"Pardon Me\" bir panik ataktan, \"Drive\" ise kontrolü eline alma kararından doğdu.",
      "Albüm 2 milyonun üzerinde sattı ve grubu Ozzfest'ten TRL'ye taşıdı. Brandon Boyd'un vokal melodileri, 2000'lerin alternatifinin daha güneşli yüzü.",
    ],
    artistInfo:
      "Incubus: Brandon Boyd (vokal), Mike Einziger (gitar), Alex Katunich / Dirk Lance (bas, bu albümde), Jose Pasillas (davul) ve DJ Kilmore.",
    members: ["Brandon Boyd – vokal", "Mike Einziger – gitar", "Dirk Lance – bas", "Jose Pasillas – davul", "DJ Kilmore – turntable"],
    funFacts: [
      "\"Drive\" klibi gölge tiyatrosuyla çekildi ve MTV'de yoğun döndü.",
      "Einziger sonradan orkestra aranjmanları da yazdı; grubun müzikal merceği genişledi.",
      "\"Pardon Me\", Boyd'un bir dergide 'out of body experience' okumasından çıktı.",
    ],
    relatedTo: ["Imagine Dragons", "Three Days Grace"],
  },
  {
    slug: "rhcp-californication",
    artist: "Red Hot Chili Peppers",
    title: "Californication",
    year: 1999,
    deezerId: 90875,
    genres: ["Alternatif rock", "Funk rock"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "John Frusciante'nin dönüş albümü: Kaliforniya melodisi, Neighbourhood ve Broken Bells dinleyicisine de hitap eder.",
    story: [
      "Frusciante'nin bağımlılıktan dönüp gruba katılması, Rick Rubin ile kaydedilen bu albümü hem daha sakin hem daha büyük yaptı. \"Scar Tissue\", \"Otherside\", \"Californication\" ve \"Around the World\" 90'ların sonunu Kaliforniya'ya bağladı.",
      "Anthony Kiedis'in sözleri şöhret, uyuşturucu ve eyaletin sahte güneşi üzerine. Albüm 16 milyondan fazla sattı.",
    ],
    artistInfo:
      "RHCP: Anthony Kiedis, Flea, John Frusciante ve Chad Smith. Frusciante'nin 1998 dönüşü, grubun en çok dinlenen dönemini başlattı.",
    members: ["Anthony Kiedis – vokal", "Flea – bas", "John Frusciante – gitar, vokal", "Chad Smith – davul"],
    funFacts: [
      "Frusciante albümden kısa süre önce neredeyse ölüyordu; dönüşü belgesel konusu oldu.",
      "\"Scar Tissue\" Grammy kazandı.",
      "Kapaktaki havuz, Kaliforniya rüyasının hem lüksünü hem boşluğunu tek karede anlatır.",
    ],
    relatedTo: ["The Neighbourhood", "Broken Bells"],
  },
  {
    slug: "audioslave-audioslave",
    artist: "Audioslave",
    title: "Audioslave",
    year: 2002,
    deezerId: 97953,
    genres: ["Hard rock", "Alternatif rock"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "Soundgarden vokalisti + Rage Against the Machine enstrümanları: Pretty Reckless ve Three Days Grace dinleyicisine birebir.",
    story: [
      "Rage Against the Machine Zack de la Rocha ayrılınca Cornell ile prova yaptı; kimya hemen tuttu. Rick Rubin prodüksiyonundaki çıkış albümü \"Cochise\", \"Like a Stone\" ve \"Show Me How to Live\" ile 2000'lerin riff rock'ını geri getirdi.",
      "Cornell'in Zeppelin'vari melodileri, Morello'nun efektli gitarıyla evlendi. Albüm 3 milyonun üzerinde sattı; grup üç albüm sonra dağıldı.",
    ],
    artistInfo:
      "Audioslave: Chris Cornell (vokal), Tom Morello (gitar), Tim Commerford (bas) ve Brad Wilk (davul). Cornell 2017'de hayata veda etti; Morello Pretty Reckless'in Death by Rock and Roll'unda da çaldı.",
    members: ["Chris Cornell – vokal, gitar", "Tom Morello – gitar", "Tim Commerford – bas", "Brad Wilk – davul"],
    funFacts: [
      "İlk isim 'Civilian'dı; hukuki sorun yüzünden Audioslave oldu.",
      "\"Like a Stone\" Cornell'in ölüm ve ötesi üzerine en sakin şarkılarından.",
      "Morello, Pretty Reckless'in \"And So It Went\"inde solo çaldı — Cornell bağı orada da sürüyor.",
    ],
    relatedTo: ["The Pretty Reckless", "Three Days Grace"],
  },
  {
    slug: "qotsa-songs-for-the-deaf",
    artist: "Queens of the Stone Age",
    title: "Songs for the Deaf",
    year: 2002,
    deezerId: 321172117,
    genres: ["Hard rock", "Alternatif rock", "Stoner rock"],
    origin: "Palm Desert, Kaliforniya, ABD",
    why: "Dave Grohl davulda, Josh Homme riff'te: Arctic Monkeys AM'in çöldeki ağabeyi.",
    story: [
      "Albüm, Kaliforniya çölünde radyo istasyonları arasında gezen bir yolculuk gibi kurgulandı; ara anons'lar gerçek DJ taklitleri. \"No One Knows\", \"Go with the Flow\" ve \"First It Giveth\" stoner rock'ı rock radyosunun tepesine çıkardı.",
      "Nick Oliveri'nin çığlıkları ve Mark Lanegan'ın konuk vokalleri albümü bir 'süper grup' hissine yaklaştırdı. Homme, Arctic Monkeys'in AM'inde geri vokal de yaptı.",
    ],
    artistInfo:
      "Queens of the Stone Age, Josh Homme'un Kyuss sonrası projesi. Bu albümde Dave Grohl davul çalıyor — Foo Fighters'ı geçici olarak beklettiği bir dönem.",
    members: ["Josh Homme – vokal, gitar", "Nick Oliveri – bas, vokal", "Dave Grohl – davul", "Mark Lanegan – vokal (konuk)"],
    funFacts: [
      "Grohl, Songs for the Deaf'i 'hayatımın davul kaydı' diye andı.",
      "\"No One Knows\" klibinde grup bir kulübede canavarlarla savaşır.",
      "Homme, Arctic Monkeys, Foo Fighters ve Iggy Pop ile de çalıştı; çöl rock'ının örümceği.",
    ],
    relatedTo: ["The Neighbourhood", "The Pretty Reckless"],
  },
  {
    slug: "the-strokes-is-this-it",
    artist: "The Strokes",
    title: "Is This It",
    year: 2001,
    deezerId: 1442557,
    genres: ["Bağımsız rock", "Garaj rock", "Post-punk canlanması"],
    origin: "New York City, ABD",
    why: "2000'ler indie'sini başlatan plak; The Neighbourhood ve Arctic Monkeys'in New York'taki kıvılcımı.",
    story: [
      "Julian Casablancas'ın boğuk vokali, Albert Hammond Jr. ve Nick Valensi'nin iç içe gitarları, Gordon Raphael'in lo-fi prodüksiyonu: New York yeraltından çıkan bu 36 dakika, İngiltere'de Arctic Monkeys'i ve ABD'de The Killers'ı ateşledi.",
      "\"Last Nite\", \"Someday\" ve \"Hard to Explain\" bir kuşağın deri ceket şarkıları oldu. Kapaktaki el fotoğrafı bazı ülkelerde uzaylı bir eldivenle değiştirildi.",
    ],
    artistInfo:
      "The Strokes: Julian Casablancas, Nick Valensi, Albert Hammond Jr., Nikolai Fraiture ve Fabrizio Moretti. Özel okul arkadaşlarından dünya sahnesine.",
    members: ["Julian Casablancas – vokal", "Nick Valensi – gitar", "Albert Hammond Jr. – gitar", "Nikolai Fraiture – bas", "Fabrizio Moretti – davul"],
    funFacts: [
      "İngiltere basımı ABD'den önce çıktı; ABD kapağı sansürlendi.",
      "Casablancas vokali, oda hoparlöründen yeniden mikrofona alarak 'telefon' dokusu verdi.",
      "Arctic Monkeys, erken demolarında Strokes etkisi taşıdıklarını hiç saklamadı.",
    ],
    relatedTo: ["The Neighbourhood"],
  },
  {
    slug: "yeah-yeah-yeahs-fever-to-tell",
    artist: "Yeah Yeah Yeahs",
    title: "Fever to Tell",
    year: 2003,
    deezerId: 49844632,
    genres: ["Bağımsız rock", "Garaj rock", "Art rock"],
    origin: "New York City, ABD",
    why: "Karen O'nun çığlığı: Pretty Reckless'in sahne duruşunun New York'taki ablası.",
    story: [
      "\"Maps\" yavaş, kırılgan bir aşk şarkısı olarak 2000'ler indie'sinin en beklenmedik hit'i oldu; \"Date with the Night\" ise tam tersi bir tükürük topu. Karen O, Nick Zinner ve Brian Chase üçlüsü The Strokes dalgasının en teatral köşesiydi.",
      "Albüm Grammy'ye aday gösterildi. Karen O'nun sahne kıyafetleri (kendi tasarladığı) ve şarap şişesi, bir dönemin görseli.",
    ],
    artistInfo:
      "Yeah Yeah Yeahs: Karen O (vokal), Nick Zinner (gitar) ve Brian Chase (davul). Üçlü, New York post-punk revival'ının en az 'erkek grubu' olan yüzü.",
    members: ["Karen O – vokal", "Nick Zinner – gitar", "Brian Chase – davul"],
    funFacts: [
      "\"Maps\", Karen O'nun o dönemki sevgilisi Angus Andrew (Liars) için yazıldı.",
      "\"Maps\" klibinde Karen gerçekten ağlar — tek take.",
      "Grup adı, prova sırasında birbirlerine söyledikleri 'yeah yeah yeah' tepkisinden geliyor.",
    ],
    relatedTo: ["The Pretty Reckless", "The Neighbourhood"],
  },
  {
    slug: "placebo-without-you-im-nothing",
    artist: "Placebo",
    title: "Without You I'm Nothing",
    year: 1998,
    deezerId: 352412657,
    genres: ["Alternatif rock", "Glam rock"],
    origin: "Londra, İngiltere",
    why: "Brian Molko'nun androjen vokali: Panic! ve Neighbourhood'un karanlık tiyatrosuna giden İngiliz yol.",
    story: [
      "İkinci albüm, \"Pure Morning\"in 'a friend in need's a friend indeed' nakaratıyla Placebo'yu Britpop sonrası İngiltere'nin gotik pop yüzü yaptı. David Bowie, başlık şarkısının düet versiyonunda konuk oldu.",
      "Molko'nun rujlu, tiz ve alaycı duruşu, 2000'ler emo'sunun sahne makyajından önce geliyordu. \"Every You Every Me\" Cruel Intentions filmine de girdi.",
    ],
    artistInfo:
      "Placebo: Brian Molko (vokal, gitar), Stefan Olsdal (bas, gitar) ve Steve Hewitt (davul, bu albümde). Molko Lüksemburg doğumlu, ABD ve İngiltere arasında büyüdü.",
    members: ["Brian Molko – vokal, gitar", "Stefan Olsdal – bas, gitar, vokal", "Steve Hewitt – davul"],
    funFacts: [
      "Bowie, Placebo'yu erken dönemde sahneye çıkardı ve düet teklif etti.",
      "\"Pure Morning\" aslında albüme son anda eklenen bir B-side'dı ve en büyük hit oldu.",
      "Cruel Intentions, \"Every You Every Me\"yi bir kuşak lise karanlığıyla eşleştirdi.",
    ],
    relatedTo: ["Panic! At the Disco", "The Neighbourhood"],
  },
  {
    slug: "rise-against-the-sufferer-and-the-witness",
    artist: "Rise Against",
    title: "The Sufferer & the Witness",
    year: 2006,
    deezerId: 689003,
    genres: ["Punk rock", "Melodik hardcore", "Alternatif rock"],
    origin: "Chicago, Illinois, ABD",
    why: "Politik pop-punk'ın en temiz prodüksiyonu: \"Prayer of the Refugee\" hâlâ bir isyan marşı.",
    story: [
      "Bill Stevenson ve Jason Livermore (Descendents/Fat Wreck kökenli) prodüksiyonundaki albüm, Rise Against'i yeraltı hardcore'dan Mainstream Rock listesine taşıdı. \"Prayer of the Refugee\", \"Ready to Fall\" ve \"The Good Left Undone\" Warped Tour'un politik kalbiydi.",
      "Tim McIlrath'ın hem çığlık hem melodi yapabilen vokali, Green Day American Idiot sonrası punk'ın daha ciddi yüzünü temsil etti.",
    ],
    artistInfo:
      "Rise Against: Tim McIlrath (vokal, gitar), Zach Blair (gitar, bu albümde Joe Principe ile birlikte), Joe Principe (bas) ve Brandon Barnes (davul). Grup vegan ve politik kimliğiyle tanınır.",
    members: ["Tim McIlrath – vokal, gitar", "Chris Chasse – gitar", "Joe Principe – bas, vokal", "Brandon Barnes – davul"],
    funFacts: [
      "\"Prayer of the Refugee\" klibi bir fabrikada çekildi; tüketim eleştirisi görsel olarak da var.",
      "Albüm Billboard 200'e 10 numaradan girdi — bir punk grubu için o yıl büyük bir açılış.",
      "McIlrath, sahnede sıkça politik konuşma yapmasıyla Warped Tour'un 'ciddi' vokalistiydi.",
    ],
    relatedTo: ["Panic! At the Disco", "Three Days Grace"],
  },
  {
    slug: "a-day-to-remember-homesick",
    artist: "A Day to Remember",
    title: "Homesick",
    year: 2009,
    deezerId: 1003343841,
    genres: ["Pop punk", "Metalcore", "Post-hardcore"],
    origin: "Ocala, Florida, ABD",
    why: "Pop-punk nakarat + breakdown: BMTH That's the Spirit'e giden Amerikan yolu.",
    story: [
      "Homesick, \"The Downfall of Us All\", \"If It Means a Lot to You\" ve \"Have Faith in Me\" ile pop-punk ve metalcore'u aynı şarkıda evlendirdi. Jeremy McKinnon'ın temiz vokali ve breakdown'lar, Warped Tour 2009'un en kalabalık çadırını yaptı.",
      "Albüm, Florida pop-punk'ı ile metalcore'un 'easycore' denen melezini ana akıma yaklaştırdı. \"If It Means a Lot to You\" hâlâ düğün ve veda şarkısı.",
    ],
    artistInfo:
      "A Day to Remember: Jeremy McKinnon (vokal), Kevin Skaff ve Neil Westfall (gitar), Joshua Woodard (bas) ve Alex Shelnutt (davul).",
    members: ["Jeremy McKinnon – vokal", "Kevin Skaff – gitar, vokal", "Neil Westfall – gitar", "Joshua Woodard – bas", "Alex Shelnutt – davul"],
    funFacts: [
      "\"The Downfall of Us All\"in açılışındaki 'na-na' korosu stadyum tezahüratı gibi yazıldı.",
      "Grup, Victory Records ile yıllarca süren bir hukuki savaş yaşadı.",
      "Homesick, ADTR'nin en çok dinlenen albümü olmaya devam ediyor.",
    ],
    relatedTo: ["Panic! At the Disco", "Three Days Grace"],
  },
  {
    slug: "starset-transmissions",
    artist: "Starset",
    title: "Transmissions",
    year: 2014,
    deezerId: 130678282,
    genres: ["Alternatif rock", "Elektronik rock", "Sinematik rock"],
    origin: "Columbus, Ohio, ABD",
    why: "Breaking Benjamin'in sinematik kuzeni: yaylılar, synth ve \"My Demons\".",
    story: [
      "Downplay'den çıkan Dustin Bates, Starset'i bir bilimkurgu kolektifi gibi kurguladı: uzay temalı sahneler, konsept hikâye, yaylılar. \"My Demons\" rock radyosunda 1 numaraya yürüdü ve grubu bir nişten çıkardı.",
      "Albüm, Bates'in elektrik mühendisliği / astronomi geçmişini rock'a çevirme projesi. Imagine Dragons'ın elektronik stadyum sesine daha karanlık, daha metal bir cevap.",
    ],
    artistInfo:
      "Starset, Dustin Bates'in yönettiği bir kolektif; sahnede kasklı müzisyenler ve yaylı dörtlüyle performans yaparlar. Columbus, Ohio çıkışlı.",
    members: ["Dustin Bates – vokal, gitar", "Brock Richards – gitar", "Ron DeChant – bas, klavye", "Adam Gilbert – davul"],
    funFacts: [
      "Bates'in akademik geçmişi gerçek: elektromanyetik üzerine çalıştı.",
      "\"My Demons\" YouTube'da yüz milyonlarca izlenen bir rock klibi.",
      "Konsept, kurgusal 'Starset Society'nin dünyaya gönderdiği iletiler üzerine kurulu.",
    ],
    relatedTo: ["Breaking Benjamin", "Imagine Dragons"],
  },
  {
    slug: "i-prevail-trauma",
    artist: "I Prevail",
    title: "TRAUMA",
    year: 2019,
    deezerId: 91333612,
    genres: ["Post-hardcore", "Alternatif metal", "Pop metal"],
    origin: "Southfield, Michigan, ABD",
    why: "Grammy adayı modern metalcore: Three Days Grace'in 2010'lar sonraki hali.",
    story: [
      "Brian Burkheiser'ın vokal kist ameliyatı ve Eric Vanlerberghe'nin çığlığı üzerine kurulu TRAUMA, \"Bow Down\" ve \"Breaking Down\" ile Grammy'de En İyi Rock Albümü ve En İyi Metal Performansı adaylığı aldı.",
      "Grup, Taylor Swift cover'ı \"Blank Space\" ile viral olup 'cover grubu' damgasını bu albümle kırdı. Pop nakarat + djent gitar, 2010'ların sonunun rock formülü.",
    ],
    artistInfo:
      "I Prevail: Brian Burkheiser (temiz vokal), Eric Vanlerberghe (çığlık/vokal), Steve Menezian (gitar), Dylan Bowman (gitar), Tony Camposeo (bas) ve Gabe Helguera (davul).",
    members: ["Brian Burkheiser – vokal", "Eric Vanlerberghe – vokal", "Steve Menezian – gitar", "Dylan Bowman – gitar", "Gabe Helguera – davul"],
    funFacts: [
      "Burkheiser albümden önce sesini kaybetme riski yaşadı; TRAUMA bu dönemin kaydı.",
      "İki Grammy adaylığı, bir metalcore grubu için 2019'da büyük bir kapı araladı.",
      "Grup Michigan'dan çıkıp Fast & Furious soundtrack'lerine kadar uzandı.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "bad-omens-the-death-of-peace-of-mind",
    artist: "Bad Omens",
    title: "THE DEATH OF PEACE OF MIND",
    year: 2022,
    deezerId: 764348781,
    genres: ["Alternatif metal", "Elektronik rock", "Post-hardcore"],
    origin: "Richmond, Virginia, ABD",
    why: "2020'lerin The Neighbourhood × Bring Me the Horizon kesişimi: \"Just Pretend\" ve başlık şarkısı.",
    story: [
      "Noah Sebastian, metalcore çıkışlı grubu R&B, elektronik ve pop vokal estetiğine çekti. Başlık şarkısı ve \"Just Pretend\" TikTok üzerinden milyonlara ulaştı; rock radyosu onları sonradan takip etti.",
      "Albüm, 2020'lerin 'alt-metal pop' dalgasının (Sleep Token, Spiritbox) Amerikan yüzü. Sebastian prodüksiyonun büyük kısmını evinde yaptı.",
    ],
    artistInfo:
      "Bad Omens: Noah Sebastian (vokal), Joakim Karlsson (gitar), Nicholas Ruffilo (gitar/bas) ve Nick Folio (davul). Richmond, Virginia kökenli.",
    members: ["Noah Sebastian – vokal, prodüksiyon", "Joakim Karlsson – gitar", "Nicholas Ruffilo – gitar, bas", "Nick Folio – davul"],
    funFacts: [
      "\"Just Pretend\" 2023'ün en çok dinlenen rock şarkılarından biri oldu.",
      "Sebastian, The Weeknd ve The Neighbourhood dinleyerek vokal prodüksiyonunu şekillendirdiğini söyledi.",
      "Grup, BMTH ile turneye çıkarak aynı keşif hattının canlı kanıtı oldu.",
    ],
    relatedTo: ["The Neighbourhood", "Three Days Grace"],
  },
  {
    slug: "in-this-moment-blood",
    artist: "In This Moment",
    title: "Blood",
    year: 2012,
    deezerId: 11329016,
    genres: ["Alternatif metal", "Hard rock", "Endüstriyel metal"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "Maria Brink'in tiyatrosu: Pretty Reckless sevenlerin bir sonraki sahne şoku.",
    story: [
      "Kevin Churko (Ozzy, Five Finger Death Punch) prodüksiyonundaki Blood, In This Moment'ı metalcore'dan endüstriyel-pop metal'e taşıdı. Başlık şarkısı Mainstream Rock'ta üst sıralara çıktı; sahne şovları taç, kan ve bale karışımı.",
      "\"Adrenalize\" ve \"Whore\" (Brink'in kelimeyi sahiplenme şarkısı) grubu festival ana sahnelerine çıkardı. 2010'ların kadın vokalli metalinin en görünür işlerinden.",
    ],
    artistInfo:
      "In This Moment: Maria Brink (vokal), Chris Howorth (gitar) ve dönen bir ritim seksiyonu. Brink, sahne tiyatrosunu Lzzy Hale ve Taylor Momsen'den daha gotik bir yere çeker.",
    members: ["Maria Brink – vokal, piyano", "Chris Howorth – gitar", "Randy Weitzel – gitar", "Travis Johnson – bas", "Tom Hane – davul"],
    funFacts: [
      "\"Blood\" Brink'in bir ilişkideki güç dinamiği üzerine; klipte taç ve merasim var.",
      "Churko, albümü Las Vegas'taki stüdyosunda kaydetti — Pretty Reckless'in de sık döndüğü bir rock şehri.",
      "Brink, Kerrang! ve Revolver kapaklarının 2010'lardaki sabit yüzlerindendi.",
    ],
    relatedTo: ["The Pretty Reckless"],
  },
  {
    slug: "flyleaf-flyleaf",
    artist: "Flyleaf",
    title: "Flyleaf",
    year: 2005,
    deezerId: 320919767,
    genres: ["Alternatif metal", "Post-grunge", "Hard rock"],
    origin: "Belton, Texas, ABD",
    why: "Lacey Sturm'un çığlığı: Evanescence ile Pretty Reckless arasında, \"I'm So Sick\" ve \"All Around Me\".",
    story: [
      "Texas'lı grubun çıkış albümü, Lacey Mosley'nin (sonradan Sturm) hem kırılgan hem ağır vokaliyle 2000'lerin Hristiyan-alternatif sınırında durdu ama rock radyosu onları mezhep dinlemeden çaldı.",
      "\"I'm So Sick\" Resident Evil: Extinction'da da kullanıldı; \"All Around Me\" Hot 100'e girdi. Albüm 2 milyonun üzerinde sattı.",
    ],
    artistInfo:
      "Flyleaf: Lacey Sturm (vokal), Sameer Bhattacharya (gitar), Jared Hartmann (gitar), Pat Seals (bas) ve James Culpepper (davul). Sturm 2012'de gruptan ayrıldı.",
    members: ["Lacey Sturm – vokal", "Sameer Bhattacharya – gitar", "Jared Hartmann – gitar", "Pat Seals – bas", "James Culpepper – davul"],
    funFacts: [
      "\"I'm So Sick\" bir öfke boşalması olarak yazıldı; radyo versiyonu biraz yumuşatıldı.",
      "Sturm, sahne korkusunu açıkça anlatan vokalistlerden; ilk turlar zor geçti.",
      "Albüm, kadın vokalli post-grunge'ın Evanescence sonrası en büyük çıkışlarından.",
    ],
    relatedTo: ["The Pretty Reckless", "Breaking Benjamin"],
  },
  {
    slug: "the-1975-a-brief-inquiry",
    artist: "The 1975",
    title: "A Brief Inquiry Into Online Relationships",
    year: 2018,
    deezerId: 79884272,
    genres: ["Pop rock", "Synth-pop", "Alternatif"],
    origin: "Manchester, İngiltere",
    why: "Matty Healy'nin internet çağı pop'u: The Neighbourhood ve Panic!'in 2010'lar Britanyalı kuzeni.",
    story: [
      "Üçüncü albüm, \"Love It If We Beat Together\", \"Sincerity Is Scary\" ve \"TOOTIMETOOTIMETOOTIME\" ile The 1975'i festival kapanış grubu yaptı. Healy, çevrimiçi aşk, sahte haber ve bağımlılık üzerine yazdı.",
      "Albüm İngiltere'de 1 numara oldu ve Mercury'ye aday gösterildi. Prodüksiyon (George Daniel ile) 80'ler sophisti-pop'undan hip-hop'a zıplar — Broken Bells dinleyicisine de tanıdık bir eklektizm.",
    ],
    artistInfo:
      "The 1975: Matty Healy (vokal), Adam Hann (gitar), Ross MacDonald (bas) ve George Daniel (davul, prodüksiyon). Wilmslow'da okul arkadaşlığı.",
    members: ["Matty Healy – vokal, gitar", "Adam Hann – gitar", "Ross MacDonald – bas", "George Daniel – davul, prodüksiyon"],
    funFacts: [
      "Grup adı, Healy'nin evindeki bir Beat kuşağı kitabı üzerindeki bir tarih notundan geliyor.",
      "\"Love It If We Beat Together\" bir umut şarkısı olarak Brexit İngiltere'sinde yazıldı.",
      "Daniel, albümün co-prodüktörü; The 1975'in sesi büyük ölçüde onun.",
    ],
    relatedTo: ["The Neighbourhood", "Panic! At the Disco"],
  },
  {
    slug: "foster-the-people-torches",
    artist: "Foster the People",
    title: "Torches",
    year: 2011,
    deezerId: 1437015,
    genres: ["Bağımsız pop", "Alternatif", "Indie pop"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "\"Pumped Up Kicks\" — Imagine Dragons ve Neighbourhood ile aynı 2011 indie-pop dalgası.",
    story: [
      "Mark Foster, reklam jingle'ı yazarak geçinirken \"Pumped Up Kicks\"i evinde üretti; şarkı bir okul şiddeti anlatısı olarak yazıldı ama dans edilebilir bir nakaratı vardı. Albüm, \"Helena Beat\" ve \"Don't Stop (Color on the Walls)\" ile 2011'in soundtrack'i oldu.",
      "Torches, The Neighbourhood'un I Love You.'sundan iki yıl önce aynı L.A. indie-pop coğrafyasını işaret etti.",
    ],
    artistInfo:
      "Foster the People: Mark Foster (vokal, klavye), Cubbie Fink (bas, bu albümde) ve Mark Pontius (davul). Foster, Yakima Washington doğumlu.",
    members: ["Mark Foster – vokal, klavye, gitar", "Cubbie Fink – bas", "Mark Pontius – davul"],
    funFacts: [
      "\"Pumped Up Kicks\"in sözleri neşeli nakaratın tam tersi; Foster bilinçli bir tuzak kurdu.",
      "Foster, şarkıyı Logic'te kendi başına üretti.",
      "Albüm Grammy'de En İyi Alternatif Albüm'e aday gösterildi.",
    ],
    relatedTo: ["Imagine Dragons", "The Neighbourhood"],
  },
  {
    slug: "awolnation-megalithic-symphony",
    artist: "AWOLNATION",
    title: "Megalithic Symphony",
    year: 2011,
    deezerId: 1527114,
    genres: ["Elektronik rock", "Alternatif", "Pop rock"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "\"Sail\" — Imagine Dragons Evolve'dan önce elektronik stadyum rock'ının kulaktan kulağa hit'i.",
    story: [
      "Aaron Bruno (eski Home Town Hero / Under the Influence of Giants) tek başına neredeyse tüm enstrümanları çalarak \"Sail\"i yazdı. Şarkı yıllar içinde yavaş yavaş patladı; Billboard Rock listesinde rekor süre kaldı.",
      "Albüm, hip-hop davulları, korolar ve rock nakaratlarını Imagine Dragons ile aynı L.A. havuzunda karıştırdı. \"Not Your Fault\" ve \"Kill Your Heroes\" diğer tekli'ler.",
    ],
    artistInfo:
      "AWOLNATION, Aaron Bruno'nun proje adı. Sahnede tam bir grup; stüdyoda çoğu zaman Bruno.",
    members: ["Aaron Bruno – vokal, prodüksiyon", "Isaac Brown – bas", "Zach Irons – gitar", "Cian Riordan – gitar, klavye"],
    funFacts: [
      "\"Sail\" rock radyosunda 79 haftadan fazla kalarak bir dönem rekoru kırdı.",
      "Şarkı çok sayıda TV reklamında ve oyun trailer'ında kullanıldı.",
      "Bruno, 'AWOL'ü eski gruplarından kaçış hali olarak seçti.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "onerepublic-native",
    artist: "OneRepublic",
    title: "Native",
    year: 2013,
    deezerId: 320454197,
    genres: ["Pop rock", "Alternatif"],
    origin: "Colorado Springs, Kolorado, ABD",
    why: "Ryan Tedder'ın stadyum pop'u: Imagine Dragons ile aynı festival posterinin diğer yarısı.",
    story: [
      "\"Counting Stars\" folk-pop nakaratıyla 2013-14'ün her yerindeydi; \"If I Lose Myself\" ve \"Something I Need\" albümü Native'i grubun en büyük kaydı yaptı. Tedder aynı dönemde Beyoncé ve Adele'e de şarkı yazıyordu.",
      "Colorado çıkışlı grup, MySpace döneminde Timbaland'in keşfiydi. Native, rock enstrümanlarını EDM drop'larıyla birleştiren '2013 festival pop'unun ders kitabı.",
    ],
    artistInfo:
      "OneRepublic: Ryan Tedder (vokal, piyano), Zach Filkins (gitar), Drew Brown (gitar), Brent Kutzle (bas, çello) ve Eddie Fisher (davul, bu albümde).",
    members: ["Ryan Tedder – vokal, piyano", "Zach Filkins – gitar, vokal", "Drew Brown – gitar", "Brent Kutzle – bas, çello", "Eddie Fisher – davul"],
    funFacts: [
      "\"Counting Stars\" İngiltere'de 1 numara oldu — ABD'den önce.",
      "Tedder, 'Apologize' döneminden beri hem grup hem hitmaker olarak çift kariyer yürüttü.",
      "Albüm adı, 'nereden geldiğimiz' anlamında Native — Colorado köklerine dönüş.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "coldplay-a-rush-of-blood",
    artist: "Coldplay",
    title: "A Rush of Blood to the Head",
    year: 2002,
    deezerId: 299821,
    genres: ["Alternatif rock", "Pop rock"],
    origin: "Londra, İngiltere",
    why: "\"Clocks\" ve \"The Scientist\": Imagine Dragons'ın piyano-stadyum çizgisinin net atası.",
    story: [
      "Parachutes'un başarısından sonra Coldplay daha büyük, daha karanlık bir albüm istedi. \"Clocks\"un piyano riffi Ken Nelson prodüksiyonunda doğdu ve Grammy'de Yılın Kaydı'nı kazandı. \"The Scientist\" geriye saran klibiyle 2000'lerin görsel hafızasına kazındı.",
      "\"In My Place\" ve \"Amsterdam\" albümü hem Brit ödüllerinin hem ABD radyosunun kapısını açtı. Sonraki yılların festival kapanış formülü burada netleşti.",
    ],
    artistInfo:
      "Coldplay: Chris Martin, Jonny Buckland, Guy Berryman ve Will Champion. University College London'da tanıştılar.",
    members: ["Chris Martin – vokal, piyano", "Jonny Buckland – gitar", "Guy Berryman – bas", "Will Champion – davul, vokal"],
    funFacts: [
      "\"Clocks\"un piyano riffi, Martin'in stüdyodan çıkarken son anda çaldığı bir taslaktı.",
      "\"The Scientist\" klibi baştan sona geriye doğru oynanır; Martin koreografiyi ters ezberledi.",
      "Albüm, 2000'lerin başında U2'nin 'büyük duygusal rock' tahtına talip oldu.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "arcade-fire-funeral",
    artist: "Arcade Fire",
    title: "Funeral",
    year: 2004,
    deezerId: 43265861,
    genres: ["Bağımsız rock", "Art rock", "Barok pop"],
    origin: "Montreal, Kanada",
    why: "Kolektif, yas ve korolar: Broken Bells ve Imagine Dragons dinleyicisine indie'nin stadyum kapısı.",
    story: [
      "Win ve Régine'in aile kayıpları albüme adını verdi. \"Wake Up\", \"Rebellion (Lies)\" ve \"Neighborhood\" serisi, Montreal'de bir kilise bodrumunda büyüyen bir kolektifi 2000'lerin en önemli indie grubu yaptı.",
      "Funeral, indie'nin 'küçük' kalmak zorunda olmadığını kanıtladı. Springsteen ve Bowie bu grubu açıkça övdü.",
    ],
    artistInfo:
      "Arcade Fire: Win Butler, Régine Chassagne, Richard Reed Parry, Tim Kingsbury, William Butler ve Jeremy Gara. Büyük, çok enstrümanlı bir sahne.",
    members: ["Win Butler – vokal, gitar", "Régine Chassagne – vokal, akordeon, davul", "Richard Reed Parry – gitar, kontrabas", "Tim Kingsbury – bas", "Jeremy Gara – davul"],
    funFacts: [
      "\"Wake Up\" korosu futbol stadyumlarında tezahürata dönüştü.",
      "Albümdeki 'Neighborhood' şarkıları, çocukluk mahallelerinin yasını tutar.",
      "Funeral, Pitchfork çağının indie kanonunun tepesine yerleşti.",
    ],
    relatedTo: ["Broken Bells", "Imagine Dragons"],
  },
  {
    slug: "mgmt-oracular-spectacular",
    artist: "MGMT",
    title: "Oracular Spectacular",
    year: 2007,
    deezerId: 71318,
    genres: ["Psikedelik pop", "Synth-pop", "Bağımsız pop"],
    origin: "Middletown, Connecticut, ABD",
    why: "\"Time to Pretend\" ve \"Kids\": Broken Bells ve Beatles psikedelisinin 2000'ler pop'u.",
    story: [
      "Wesleyan mezunu Andrew VanWyngarden ve Ben Goldwasser, Dave Fridmann (Flaming Lips) ile ilk albümlerini kaydetti. \"Electric Feel\", \"Kids\" ve \"Time to Pretend\" bir üniversite internat şarkıları kuşağı yarattı.",
      "Grup sonradan bilinçli olarak hit yazmayı bıraktı; bu albüm onların pop'a verdiği (ve sonra kaçtığı) söz.",
    ],
    artistInfo:
      "MGMT bir ikili: VanWyngarden (vokal, gitar) ve Goldwasser (klavye). Sahnede genişler, stüdyoda iki kişi kalırlar.",
    members: ["Andrew VanWyngarden – vokal, gitar", "Ben Goldwasser – klavye, vokal"],
    funFacts: [
      "\"Kids\" yıllar sonra TikTok'ta ikinci bir hayat yaşadı.",
      "Fridmann'ın prodüksiyonu, albüme psikedelik bir 'şişme' verdi.",
      "İkili, şöhretten rahatsız olduklarını sonraki albümlerde açıkça işledi.",
    ],
    relatedTo: ["Broken Bells", "The Beatles"],
  },
  {
    slug: "vampire-weekend-modern-vampires",
    artist: "Vampire Weekend",
    title: "Modern Vampires of the City",
    year: 2013,
    deezerId: 176532302,
    genres: ["Bağımsız pop", "Bağımsız rock", "Art pop"],
    origin: "New York City, ABD",
    why: "Ezra Koenig'in sözcük oyunu ve kilise org'u: Beatles melodisi + Neighbourhood kentsel hüznü.",
    story: [
      "Üçüncü albüm, Ariel Rechtshaid prodüksiyonunda yaşlanma, inanç ve New York üzerine. \"Diane Young\", \"Step\" ve \"Hannah Hunt\" Vampire Weekend'i kampüs grubundan yetişkin bir grup yaptı.",
      "Albüm Grammy'de En İyi Alternatif Albüm kazandı. Rostam Batmanglij'in son VW albümü; ayrılığından sonra Koenig bayrağı taşıdı.",
    ],
    artistInfo:
      "Vampire Weekend: Ezra Koenig (vokal, gitar), Rostam Batmanglij (klavye, prodüksiyon), Chris Baio (bas) ve Chris Tomson (davul). Columbia Üniversitesi kökenli.",
    members: ["Ezra Koenig – vokal, gitar", "Rostam Batmanglij – klavye, gitar", "Chris Baio – bas", "Chris Tomson – davul"],
    funFacts: [
      "\"Hannah Hunt\" Koenig'in yıllarca cebinde taşıdığı bir şarkıydı.",
      "Albüm kapağı, New York'ta yaşlı bir çiftin fotoğrafı — gençlik grubunun veda kartı gibi.",
      "Grammy, VW'nin 'kampüs worldbeat' imajını geride bıraktığının resmi onayı oldu.",
    ],
    relatedTo: ["Broken Bells", "The Beatles"],
  },
  {
    slug: "tame-impala-lonerism",
    artist: "Tame Impala",
    title: "Lonerism",
    year: 2012,
    deezerId: 5946143,
    genres: ["Psikedelik pop", "Psikedelik rock", "Alternatif"],
    origin: "Perth, Avustralya",
    why: "Kevin Parker'ın ev stüdyosu Beatles'ı: Broken Bells ve Imagine Dragons'ın psikedelik kapısı.",
    story: [
      "Parker neredeyse her enstrümanı Perth'teki evinde çaldı. \"Elephant\", \"Feels Like We Only Go Backwards\" ve \"Mind Mischief\" 2010'ların festival psikedelisini tanımladı.",
      "Lonerism, yalnızlık ve kalabalık korkusu üzerine. Parker sonradan Rihanna ve Lady Gaga'ya da prodüksiyon yaptı; bu albüm hâlâ onun en 'rock' kaydı.",
    ],
    artistInfo:
      "Tame Impala stüdyoda Kevin Parker'dır; sahnede tam bir grup. Perth'in dünyadan kopukluğu, sese de işlenmiş durumda.",
    members: ["Kevin Parker – vokal, tüm enstrümanlar, prodüksiyon"],
    funFacts: [
      "\"Elephant\" bir riff'in üzerine tek take davulla kaydedildi.",
      "Parker, The Beatles'ın Magical Mystery Tour'unu sıkça referans verir.",
      "Albüm, Grammy'de En İyi Alternatif Albüm'e aday gösterildi.",
    ],
    relatedTo: ["Broken Bells", "The Beatles"],
  },
  {
    slug: "portugal-the-man-woodstock",
    artist: "Portugal. The Man",
    title: "Woodstock",
    year: 2017,
    deezerId: 42880391,
    genres: ["Alternatif", "Pop rock", "Psikedelik pop"],
    origin: "Wasilla, Alaska, ABD",
    why: "\"Feel It Still\" — Danger Mouse / Broken Bells eksenine yakın, yazın her yerde olan psikedelik pop.",
    story: [
      "Yıllarca niş psikedelik rock yapan grup, John Hill ve Danger Mouse ile (bazı parçalarda) daha kısa, daha nakaratlı şarkılar yazdı. \"Feel It Still\" 1960'lar soul'undan örnek alıp 2017'nin en çok çalınan şarkılarından biri oldu.",
      "Albüm adı, bir Woodstock hayali ve Amerikan karşı kültür nostaljisi. Grammy'de En İyi Pop Düosu/Grup Performansı kazandı.",
    ],
    artistInfo:
      "Portugal. The Man: John Gourley (vokal, gitar) ve Zoe Manville çevresinde dönen bir Alaska/Portland kolektifi. Gourley, Wasilla'dan (Sarah Palin'in kasabası) çıkar.",
    members: ["John Gourley – vokal, gitar", "Zach Carper – davul", "Whoopie Dorough – klavye", "Eric Howk – gitar"],
    funFacts: [
      "\"Feel It Still\", The Show Stoppers'ın \"Ain't Gonna Lie\" bas hattından ilham alır.",
      "Şarkı Hot 100'de 1 numaraya çok yaklaştı ve Alternative'de rekor kırdı.",
      "Danger Mouse'un Broken Bells'i sevenler bu prodüksiyon dokusunu tanır.",
    ],
    relatedTo: ["Broken Bells", "Imagine Dragons"],
  },
  {
    slug: "white-stripes-elephant",
    artist: "The White Stripes",
    title: "Elephant",
    year: 2003,
    deezerId: 175927162,
    genres: ["Garaj rock", "Alternatif rock", "Blues rock"],
    origin: "Detroit, Michigan, ABD",
    why: "\"Seven Nation Army\" riffti futbol stadyumuna girdi; Pretty Reckless ve Royal Blood'ın iki kişilik cesaretinin abisi.",
    story: [
      "Jack ve Meg White, Elephant'ı Londra'daki Toe Rag stüdyosunda, 1960'lar ekipmanıyla kaydetti. \"Seven Nation Army\"nin tek notalık bas benzeri riffti (aslında bir gitar + oktav pedal) 21. yüzyılın tezahüratı oldu.",
      "\"The Hardest Button to Button\" ve \"I Just Don't Know What to Do with Myself\" (Dusty Springfield cover) albümü Grammy'li yaptı. Kırmızı-beyaz-siyah görsel disiplin, The Neighbourhood'un siyah-beyaz dönemini andırır.",
    ],
    artistInfo:
      "The White Stripes: Jack White (vokal, gitar) ve Meg White (davul). Evliymiş gibi sunuldular, kardeş gibi de; gerçek hikâye daha karışık. Grup 2011'de bitti.",
    members: ["Jack White – vokal, gitar, piyano", "Meg White – davul"],
    funFacts: [
      "\"Seven Nation Army\" adı, Jack'in çocukken 'Salvation Army'yi yanlış duyuşundan.",
      "Albüm 8 kanallı analog teybe, dijital olmadan kaydedildi.",
      "Riff, Avrupa futbolunun gayriresmi marşı haline geldi.",
    ],
    relatedTo: ["The Pretty Reckless", "Broken Bells"],
  },
  {
    slug: "oasis-morning-glory",
    artist: "Oasis",
    title: "What's the Story Morning Glory?",
    year: 1995,
    deezerId: 153406392,
    genres: ["Britpop", "Alternatif rock", "Rock"],
    origin: "Manchester, İngiltere",
    why: "Beatles tapınmasının 90'lar hali: \"Wonderwall\" ve \"Don't Look Back in Anger\".",
    story: [
      "Noel Gallagher şarkı yazdı, Liam söyledi, Owen Morris duvar gibi bir ses verdi. \"Wonderwall\", \"Don't Look Back in Anger\", \"Champagne Supernova\" ve başlık şarkısı Britpop'ı stadyum ölçeğine taşıdı.",
      "Albüm İngiltere'de 90'ların en çok satanlarından. Kardeş kavgası efsanenin parçası; müzik, Lennon/McCartney hayranlığının kaba ve büyük bir devamı.",
    ],
    artistInfo:
      "Oasis: Liam Gallagher (vokal), Noel Gallagher (gitar, vokal), Paul 'Bonehead' Arthurs (gitar), Paul McGuigan (bas) ve Alan White (davul, bu albümde).",
    members: ["Liam Gallagher – vokal", "Noel Gallagher – gitar, vokal", "Bonehead – gitar", "Paul McGuigan – bas", "Alan White – davul"],
    funFacts: [
      "\"Don't Look Back in Anger\"in piyano girişi, Lennon'ın \"Imagine\"ına bilinçli bir selam.",
      "\"Wonderwall\" adı, George Harrison'ın bir film projesinden geliyor.",
      "Knebworth 1996 konserleri, 250.000 kişilik bir Britpop taç giyme töreniydi.",
    ],
    relatedTo: ["The Beatles", "Imagine Dragons"],
  },
  {
    slug: "blur-parklife",
    artist: "Blur",
    title: "Parklife",
    year: 1994,
    deezerId: 4351521,
    genres: ["Britpop", "Alternatif rock", "Art pop"],
    origin: "Londra, İngiltere",
    why: "Damon Albarn'ın gözlem defteri — Gorillaz'dan önce; Broken Bells ve Beatles çizgisine Londra aksanı.",
    story: [
      "Parklife, İngiltere'nin banliyö hayatını karakter şarkılarıyla anlattı. \"Girls & Boys\", \"Parklife\" (Phil Daniels'ın konuşmasıyla) ve \"End of a Century\" Britpop'un 'güneyli, sanat okulu' kutbunu temsil etti; Oasis kuzeyli işçi sınıfıydı.",
      "Stephen Street prodüksiyonu, Kinks ve Small Faces hayranlığını 90'lara çevirdi. Albüm dört Brit Ödülü kazandı.",
    ],
    artistInfo:
      "Blur: Damon Albarn (vokal, klavye), Graham Coxon (gitar), Alex James (bas) ve Dave Rowntree (davul). Albarn, 2000'lerde Gorillaz'ı kurdu.",
    members: ["Damon Albarn – vokal, klavye", "Graham Coxon – gitar, vokal", "Alex James – bas", "Dave Rowntree – davul"],
    funFacts: [
      "\"Parklife\"teki konuşan ses, Quadrophenia aktörü Phil Daniels.",
      "Oasis ile 'The Battle of Britpop' 1995'te iki single'ın aynı gün çıkmasıyla zirve yaptı.",
      "Coxon'ın gitarı, Blur'u düz pop'tan art-rock'a çeken unsur.",
    ],
    relatedTo: ["The Beatles", "Broken Bells"],
  },
  {
    slug: "ghost-meliora",
    artist: "Ghost",
    title: "Meliora",
    year: 2015,
    deezerId: 320941677,
    genres: ["Hard rock", "Heavy metal", "Pop rock"],
    origin: "Linköping, İsveç",
    why: "Papa Emeritus'un katedral pop-metali: Panic!'in tiyatrosu + Pretty Reckless'in riff'i.",
    story: [
      "İsveçli (uzun süre isimsiz) kolektifin üçüncü albümü, \"Cirice\" ile Grammy kazandı. Klasik rock riff'leri, ABBA melodileri ve satanik kilise tiyatrosu — absürt ve ciddi aynı anda.",
      "Tobias Forge'un Papa Emeritus karakteri, konserleri bir ayine çevirdi. \"He Is\" ve \"From the Pinnacle to the Pit\" albümü metal dinlemeyenlere de açtı.",
    ],
    artistInfo:
      "Ghost, Tobias Forge'un (vokal) Nameless Ghouls ile sahne aldığı bir proje. Kimlikler 2017'ye kadar gizemli tutuldu.",
    members: ["Tobias Forge (Papa Emeritus III) – vokal", "Nameless Ghouls – gitar, bas, davul, klavye"],
    funFacts: [
      "\"Cirice\" 2016'da En İyi Metal Performansı Grammy'sini aldı.",
      "Forge, ABBA ve Boston'ı metal kadar etkilendiği isimler olarak sayar.",
      "Sahne şovu, Panic!'in vodvil tiyatrosuna metal makyajı sürmüş hali gibi durur.",
    ],
    relatedTo: ["Panic! At the Disco", "The Pretty Reckless"],
  },
  {
    slug: "palaye-royale-boom-boom-room",
    artist: "Palaye Royale",
    title: "Boom Boom Room (Side A)",
    year: 2016,
    deezerId: 763919611,
    genres: ["Alternatif rock", "Glam rock", "Punk rock"],
    origin: "Las Vegas, Nevada, ABD",
    why: "Vegas'tan çıkan glam-punk kardeşler: Panic! ve Pretty Reckless'in genç kuzeni.",
    story: [
      "Kordestani kardeşler (Remington, Sebastian, Emerson) Las Vegas'ta The Kents adıyla başlayıp Palaye Royale oldular. İlk albüm, 70'ler glam estetiğini (ama 70'ler şarkıları değil, 2010'lar sahne punk'ı) \"Don't Feel Quite Right\" ve \"Mr. Doctor Man\" ile sundu.",
      "Sahnedeki makyaj, dantel ve kaos, Warped Tour sonrası kuşağın 'rock yıldızı' özlemini doldurdu. Panic!'in Las Vegas çıkışına bir nesil sonra selam.",
    ],
    artistInfo:
      "Palaye Royale: Remington Leith (vokal), Sebastian Danzig (gitar) ve Emerson Barrett (davul). Üç kardeş, Kanada-İran kökenli, Vegas'ta büyümüş.",
    members: ["Remington Leith – vokal", "Sebastian Danzig – gitar", "Emerson Barrett – davul"],
    funFacts: [
      "Grup adı, New York'taki Palais Royale balo salonundan esinlenir.",
      "Emerson aynı zamanda görsel sanatçı; kliplerin estetiğini büyük ölçüde o kurar.",
      "Vegas kökeni, Panic! ile aynı şehirden iki farklı tiyatro-rock kuşağı demek.",
    ],
    relatedTo: ["Panic! At the Disco", "The Pretty Reckless"],
  },
  {
    slug: "red-end-of-silence",
    artist: "Red",
    title: "End of Silence",
    year: 2006,
    deezerId: 558507,
    genres: ["Alternatif metal", "Post-grunge", "Hard rock"],
    origin: "Nashville, Tennessee, ABD",
    why: "Breaking Benjamin'in yaylılı kuzeni: \"Breathe Into Me\" hâlâ rock radyosunun karanlık baladı.",
    story: [
      "Nashville'li kardeşler (Anthony ve Randy Armstrong) ile Michael Barnes, yaylıları nu-metal/post-grunge'a kattı. \"Breathe Into Me\" ve \"Let Go\" Hristiyan rock pazarında başlayıp Mainstream Rock listesine taştı.",
      "Jasen Rauch bu dönemde Red'in gitaristiydi; sonradan Breaking Benjamin'e geçti — iki grup arasındaki kadro köprüsü birebir.",
    ],
    artistInfo:
      "Red: Michael Barnes (vokal), Anthony Armstrong (gitar), Randy Armstrong (bas) ve Jasen Rauch (gitar, bu albümde). Rauch, Dear Agony ve Dark Before Dawn'da Breaking Benjamin'de.",
    members: ["Michael Barnes – vokal", "Anthony Armstrong – gitar", "Jasen Rauch – gitar", "Randy Armstrong – bas"],
    funFacts: [
      "Jasen Rauch, Red'den Breaking Benjamin'e geçti; Dark Before Dawn'ın mimarlarından.",
      "\"Breathe Into Me\" yaylı girişi, post-grunge'da sinema hissi arayanlara birebir.",
      "Grup, Nashville'in Hristiyan müzik altyapısından çıkıp seküler rock radyosuna geçti.",
    ],
    relatedTo: ["Breaking Benjamin"],
  },
  {
    slug: "crossfade-crossfade",
    artist: "Crossfade",
    title: "Crossfade",
    year: 2004,
    deezerId: 74907,
    genres: ["Post-grunge", "Alternatif metal", "Hard rock"],
    origin: "Columbia, Güney Karolina, ABD",
    why: "\"Cold\" — 2004 rock radyosunun Three Days Grace yanındaki diğer sabit şarkısı.",
    story: [
      "The Nothing / Sugardaddy Superstar adlarından sonra Crossfade, Columbia Records ile çıkış albümünü yayımladı. \"Cold\" Mainstream Rock'ta uzun süre zirveye yakın kaldı; \"Colors\" ve \"So Far Away\" onu izledi.",
      "Ed Sloan'ın hem temiz hem çığlık vokali, 2000'lerin post-grunge formülünün ders kitabı. Grup bir daha bu ölçeği tutturamadı; bu albüm bir dönem kapsülü.",
    ],
    artistInfo:
      "Crossfade: Ed Sloan (vokal, gitar), Mitch James (bas) ve Brian Geiger (davul, bu albümde). Güney Karolina'nın 2000'ler rock radyosu yüzü.",
    members: ["Ed Sloan – vokal, gitar", "Tony Byroads – vokal, gitar, turntable", "Mitch James – bas, vokal", "Brian Geiger – davul"],
    funFacts: [
      "\"Cold\" klibi karlı bir ormanda çekildi; şarkının adı görsele birebir yansıdı.",
      "Albüm ABD'de platin sertifika aldı.",
      "Byroads'un turntable katmanı, nu metal'in 2004'teki son dalgasının izi.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "all-american-rejects-move-along",
    artist: "The All-American Rejects",
    title: "Move Along",
    year: 2005,
    deezerId: 1026316522,
    genres: ["Pop punk", "Emo pop", "Alternatif rock"],
    origin: "Stillwater, Oklahoma, ABD",
    why: "\"Dirty Little Secret\" ve \"Move Along\": Panic! ile aynı 2005 pop-punk yazı.",
    story: [
      "Oklahoma'lı dörtlünün ikinci albümü, Tyson Ritter'ın teatral vokali ve Nick Wheeler'ın kalın gitarlarıyla TRL çağını yakaladı. Başlık şarkısı bir anti-intihar cesaret marşı olarak yazıldı; \"It Ends Tonight\" baladı düğün playlist'lerine girdi.",
      "Albüm 2 milyonun üzerinde sattı. Fueled by Ramen değil ama aynı korsan CD / Myspace kuşağı.",
    ],
    artistInfo:
      "The All-American Rejects: Tyson Ritter (vokal, bas), Nick Wheeler (gitar), Mike Kennerty (gitar) ve Chris Gaylor (davul).",
    members: ["Tyson Ritter – vokal, bas", "Nick Wheeler – gitar, vokal", "Mike Kennerty – gitar", "Chris Gaylor – davul"],
    funFacts: [
      "\"Move Along\"ın klibinde grup bir evin duvarlarını delerek çalıyor.",
      "Ritter aynı zamanda oyuncu; albüm sonrası Hollywood'a da kaydı.",
      "\"Dirty Little Secret\" bir dedikodu şarkısı olarak yazıldı, radyo onu aşk şarkısı sandı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "simple-plan-still-not-getting-any",
    artist: "Simple Plan",
    title: "Still Not Getting Any...",
    year: 2004,
    deezerId: 85526,
    genres: ["Pop punk", "Alternatif rock"],
    origin: "Montreal, Kanada",
    why: "Kanadalı pop-punk'ın en parlak ikinci albümü; Three Days Grace ile aynı ülkeden, daha şekerli bir kuzen.",
    story: [
      "\"Welcome to My Life\" ergen yabancılaşmasının 2004'teki resmi şarkısı oldu; \"Shut Up!\" ve \"Crazy\" MTV'de döndü. Bob Rock (Metallica, Mötley Crüe) prodüksiyonu, pop-punk'a beklenmedik bir ağırlık verdi.",
      "Montreal'li beşli, No Pads, No Helmets... ile açtıkları kapıyı bu albümle stadyum ön grupluğuna çevirdi.",
    ],
    artistInfo:
      "Simple Plan: Pierre Bouvier (vokal), Sébastien Lefebvre ve Jeff Stinco (gitar), David Desrosiers (bas, bu albümde) ve Chuck Comeau (davul).",
    members: ["Pierre Bouvier – vokal", "Jeff Stinco – gitar", "Sébastien Lefebvre – gitar, vokal", "David Desrosiers – bas, vokal", "Chuck Comeau – davul"],
    funFacts: [
      "Bob Rock'ın prodüksiyonu, bazı hayranlara 'çok cilalı' geldi; radyo tam tersini sevdi.",
      "\"Welcome to My Life\" klibi ev içi gerilim tablolarıyla dönemin TRL estetiğini yansıtır.",
      "Bouvier ve Comeau, Reset adlı punk grubundan geliyor; Simple Plan o kökün pop'a evrimi.",
    ],
    relatedTo: ["Panic! At the Disco", "Three Days Grace"],
  },
  {
    slug: "mayday-parade-a-lesson-in-romantics",
    artist: "Mayday Parade",
    title: "A Lesson in Romantics",
    year: 2007,
    deezerId: 12707422,
    genres: ["Emo pop", "Pop punk"],
    origin: "Tallahassee, Florida, ABD",
    why: "\"Jamie All Over\" ve \"Miserable at Best\": 2007 emo'sunun en çok cover'lanan aşk defteri.",
    story: [
      "Kid Named Florida ve DownUpDown birleşmesinden doğan grup, Fearless Records ile ilk albümlerini yayımladı. Jason Lancaster albümden hemen sonra ayrıldı; onun ve Derek Sanders'ın iç içe vokalleri kaydın kalbi.",
      "\"When I Get Home, You're So Dead\" ve \"I'd Hate\" Warped Tour 2007'nin çadır şarkılarıydı. Albüm, bir kuşak Tumblr'ın sesi oldu.",
    ],
    artistInfo:
      "Mayday Parade: Derek Sanders (vokal), Alex Garcia ve Brooks Betts (gitar), Jeremy Lenzo (bas) ve Jake Bundrick (davul, vokal). Lancaster yalnızca bu albümde ikinci vokal.",
    members: ["Derek Sanders – vokal, piyano", "Jason Lancaster – vokal, gitar", "Alex Garcia – gitar", "Brooks Betts – gitar", "Jeremy Lenzo – bas", "Jake Bundrick – davul, vokal"],
    funFacts: [
      "Lancaster, albüm taze çıkmışken gruptan ayrıldı; hayranlar hâlâ 'o kadroyu' arar.",
      "\"Miserable at Best\" akustikleri mezuniyet ve veda videosu klasiği.",
      "Fearless Records'un 2000'lerin sonundaki emo katalogunun köşe taşı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "sleep-token-take-me-back-to-eden",
    artist: "Sleep Token",
    title: "Take Me Back to Eden",
    year: 2023,
    deezerId: 403397427,
    genres: ["Alternatif metal", "Alternatif R&B", "Progresif metal"],
    origin: "Londra, İngiltere",
    why: "Maskeli, türler arası ve viral: Neighbourhood'un karanlığı + Three Days Grace'in ağırlığı, 2020'ler formu.",
    story: [
      "Vessel'ın kimliği gizlenen kolektifi, R&B, djent, piano ballad ve rap'i aynı şarkıda birleştirdi. \"The Summoning\", \"Rain\" ve \"Vore\" 2023'ün rock/metal tartışmasını onlar belirledi.",
      "Albüm İngiltere'de 3 numaraya çıktı. Sahne bir ayin; hayranlar 'Worship' diye hitap eder. Bad Omens ile aynı keşif hattının Britanyalı kutbu.",
    ],
    artistInfo:
      "Sleep Token: Vessel (vokal) ve II, III, IV kod adlı üyeler. Yüzler maskeli; röportaj yok, mitos var.",
    members: ["Vessel – vokal, gitar, piyano", "II – davul", "III – bas", "IV – gitar"],
    funFacts: [
      "\"The Summoning\" ortasında bir R&B break'i var; metal dinleyicisini böldü, yeni dinleyici getirdi.",
      "Grup, Sleep adlı bir tanrıya hizmet eden bir tapınak kurgusu üzerine kurulu.",
      "Take Me Back to Eden, birçok 2023 yıl sonu listesinde 'yılın metal albümü' seçildi.",
    ],
    relatedTo: ["The Neighbourhood", "Three Days Grace"],
  },
  {
    slug: "the-warning-error",
    artist: "The Warning",
    title: "Error",
    year: 2022,
    deezerId: 328131427,
    genres: ["Hard rock", "Alternatif rock"],
    origin: "Monterrey, Meksika",
    why: "Üç kız kardeş, Metallica'nın övdüğü riff'ler: Pretty Reckless sevenlerin 2020'ler keşfi.",
    story: [
      "Villarreal kardeşler (Daniela, Paulina, Alejandra) çocukken YouTube'da Metallica cover'ı çekip Metallica'nın kendi kanallarında paylaşılmasıyla dünyaya duyuldu. Error, 'internet fenomeninden' ciddi bir hard rock grubuna geçiş albümü.",
      "\"Money\", \"Enter Sandman\" değil kendi şarkılarıyla stadyum açtılar. İspanyolca-İngilizce çift dilli bir Meksika rock'ı, 2020'lerin en sevindirici çıkışlarından.",
    ],
    artistInfo:
      "The Warning: Dany (gitar, vokal), Pau (davul, vokal) ve Ale (bas, vokal). Monterrey, Nuevo León.",
    members: ["Daniela Villarreal – gitar, vokal", "Paulina Villarreal – davul, vokal", "Alejandra Villarreal – bas, vokal"],
    funFacts: [
      "Metallica, kızların çocukluk cover'ını resmen paylaştı; yıllar sonra aynı sahnede çaldılar.",
      "Üçü de vokal yapabiliyor; sahne içi uyum bir aile grubunun avantajı.",
      "Error, Latin Grammy'ye de adaylık kapısı araladı.",
    ],
    relatedTo: ["The Pretty Reckless"],
  },
  {
    slug: "dorothy-rockisdead",
    artist: "Dorothy",
    title: "ROCKISDEAD",
    year: 2016,
    deezerId: 13419849,
    genres: ["Hard rock", "Blues rock"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "Dorothy Martin'in blues çığlığı: Pretty Reckless'in Going to Hell döneminin L.A. komşusu.",
    story: [
      "Linda Perry'nin (4 Non Blondes, Pink söz yazarı) keşfettiği Dorothy, ROCKISDEAD ile 70'ler blues-rock'ını (ama 70'ler repertuarını değil) 2016 sahnesine getirdi. \"Raise Hell\" ve \"After Midnight\" rock radyosunda döndü.",
      "Sahne duruşu — uzun manto, yalın ayak, viski odaklı imaj — Taylor Momsen'in New York tiyatrosuna karşı L.A. blues'u.",
    ],
    artistInfo:
      "Dorothy: Dorothy Martin (vokal) ve dönen bir L.A. grubu. Martin, Kuzey Karolina doğumlu; L.A.'de sahne aldı.",
    members: ["Dorothy Martin – vokal", "Pete Verre – gitar", "Nick Maybury – gitar", "Eli Wulfmeier – gitar"],
    funFacts: [
      "Linda Perry hem mentor hem bazı şarkıların ortak yazarı.",
      "\"Raise Hell\" Gunpowder & Sky / rock playlist'lerinin 2016 sabitlerinden.",
      "Martin, sahnede yalın ayak şarkı söylemesiyle tanınır.",
    ],
    relatedTo: ["The Pretty Reckless"],
  },
  {
    slug: "x-ambassadors-vhs",
    artist: "X Ambassadors",
    title: "VHS",
    year: 2015,
    deezerId: 10632088,
    genres: ["Alternatif", "Pop rock", "Indie pop"],
    origin: "Ithaca, New York, ABD",
    why: "\"Renegades\" — Imagine Dragons'ın KIDinaKORNER etiket arkadaşının çıkış albümü.",
    story: [
      "Alex Da Kid (Imagine Dragons'ı da patlatan prodüktör) X Ambassadors'ı aynı etikete aldı. \"Renegades\" 2015'in reklam ve spor montaj marşı oldu; \"Unsteady\" ise bir ailenin dağılma baladı.",
      "Sam Harris'in biraz boğuk, biraz gospel vokali, Imagine Dragons ile aynı stadyum pop-rock rafında durur ama daha blueslu.",
    ],
    artistInfo:
      "X Ambassadors: Sam Harris (vokal), Casey Harris (klavye) ve Adam Levin (davul). Casey görme engelli; sahnedeki klavye düzeni buna göre kurulu.",
    members: ["Sam Harris – vokal, gitar", "Casey Harris – klavye", "Adam Levin – davul"],
    funFacts: [
      "Casey Harris doğuştan kör; grubun sahne şovunun bir parçası klavyesinin etrafında döner.",
      "\"Renegades\" Jeep reklamıyla patladı — 2010'ların klasik 'sync' başarı hikâyesi.",
      "KIDinaKORNER, Imagine Dragons ve X Ambassadors'ı aynı çatıda tuttu.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "the-xx-xx",
    artist: "The xx",
    title: "xx",
    year: 2009,
    deezerId: 355921,
    genres: ["Bağımsız pop", "Dream pop", "Alternatif"],
    origin: "Londra, İngiltere",
    why: "Fısıltı, boşluk ve gece: The Neighbourhood'un I Love You. estetiğinin Londra'daki ablası.",
    story: [
      "Romy Madley Croft ve Oliver Sim'in fısıltılı düetleri, Jamie xx'in minimal beat'leriyle 2009'un en etkili çıkış albümü oldu. \"Intro\", \"Crystalised\" ve \"Islands\" dizi ve reklamların da favorisi haline geldi.",
      "Albüm Mercury Ödülü kazandı. Sessizlik, bir enstrüman gibi kullanıldı — Neighbourhood'un siyah-beyaz dönemiyle aynı duygusal palet.",
    ],
    artistInfo:
      "The xx: Romy Madley Croft (vokal, gitar), Oliver Sim (vokal, bas) ve Jamie Smith (Jamie xx, beat'ler). Putney'de okul arkadaşları; üçüncü üye Baria Qureshi erken ayrıldı.",
    members: ["Romy Madley Croft – vokal, gitar", "Oliver Sim – vokal, bas", "Jamie xx – beat, prodüksiyon"],
    funFacts: [
      "\"Intro\" yıllarca BBC ve Netflix jeneriklerinin de facto müziği oldu.",
      "Üçlü, şarkıları neredeyse fısıltıyla kaydetti; stüdyo sessizliği albümün parçası.",
      "Jamie xx sonradan In Colour ile solo patladı; The xx aralıklı devam etti.",
    ],
    relatedTo: ["The Neighbourhood", "Broken Bells"],
  },
  {
    slug: "walk-the-moon-talking-is-hard",
    artist: "Walk the Moon",
    title: "Talking Is Hard",
    year: 2014,
    deezerId: 9154869,
    genres: ["Pop rock", "Alternatif", "Indie pop"],
    origin: "Cincinnati, Ohio, ABD",
    why: "\"Shut Up and Dance\" — Imagine Dragons Evolve ile aynı stadyum-neşe rafı.",
    story: [
      "Nicholas Petricca'nın \"Shut Up and Dance\"i bir kulüpte kız arkadaşının söylediği cümleden çıktı ve 2015'in her düğününün şarkısı oldu. Albüm, \"Anna Sun\" dönemindeki indie'den daha büyük, daha 80'ler davullu bir pop-rock'a kaydı.",
      "Talking Is Hard, festival ana sahnelerinin 'herkes zıplasın' kaydı. Imagine Dragons dinleyicisinin daha pembe, daha diskoya yakın gecesi.",
    ],
    artistInfo:
      "Walk the Moon: Nicholas Petricca (vokal, klavye), Eli Maiman (gitar), Kevin Ray (bas) ve Sean Waugaman (davul). Kenyon College kökenli.",
    members: ["Nicholas Petricca – vokal, klavye", "Eli Maiman – gitar, vokal", "Kevin Ray – bas", "Sean Waugaman – davul"],
    funFacts: [
      "\"Shut Up and Dance\" Hot 100'de 4 numaraya kadar çıktı.",
      "Grup adı, The Police'in \"Walking on the Moon\"una gönderme.",
      "Petricca sahnede yüz boyasıyla 80'ler new wave görseline yaslanır.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
];
