import type { Album } from "./types";

/**
 * Albums by artists that sit next to the listener's favourites: same producers,
 * same scenes, shared tours, or an obvious sonic kinship.
 */
export const similarAlbums: Album[] = [
  {
    slug: "linkin-park-hybrid-theory",
    artist: "Linkin Park",
    title: "Hybrid Theory",
    year: 2000,
    deezerId: 260137,
    genres: ["Nu metal", "Alternatif rock", "Rap rock"],
    origin: "Agoura Hills, Kaliforniya, ABD",
    why: "Three Days Grace ve Breaking Benjamin'i seviyorsan, 2000'lerin rock sesini kuran albüm bu.",
    story: [
      "Xero adıyla yıllarca reddedilen grup, 1999'da Chester Bennington'ın kadroya katılmasıyla dönüştü. Bennington, Arizona'dan gönderdiği demo kasetini doğum gününde kaydetmişti; grubu dinleyen Warner Bros. sonunda imza attı.",
      "Don Gilmore prodüktörlüğündeki Hybrid Theory, \"One Step Closer\", \"Crawling\" (Grammy ödüllü), \"Papercut\" ve \"In the End\" ile 2001'in ABD'de en çok satan albümü oldu ve 21. yüzyılın en çok satan çıkış albümlerinden biri hâline geldi. Shinoda'nın rap'i ile Bennington'ın çığlığı, bir kuşağın ergenlik sesi oldu.",
    ],
    artistInfo:
      "Linkin Park: Chester Bennington (vokal), Mike Shinoda (rap/vokal, klavye), Brad Delson (gitar), Joe Hahn (turntable), Rob Bourdon (davul) ve Dave 'Phoenix' Farrell (bas). Farrell albüm kaydedilirken başka bir grupla turnede olduğu için bas partileri stüdyo müzisyenleri ve Delson tarafından çalındı.",
    members: ["Chester Bennington – vokal", "Mike Shinoda – vokal, rap, klavye", "Brad Delson – gitar", "Joe Hahn – turntable, sample", "Rob Bourdon – davul", "Dave Farrell – bas (turne)"],
    funFacts: [
      "Grup adı Santa Monica'daki Lincoln Park'tan geliyor; 'linkinpark.com' alan adı daha ucuz olduğu için yazımı değiştirildi.",
      "\"In the End\" Shinoda'nın en sevmediği şarkıydı; albüme girmesini bile istememişti.",
      "Albüm çıktığı yıl 4,8 milyon satarak 2001'in ABD'de en çok satan albümü oldu.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "linkin-park-meteora",
    artist: "Linkin Park",
    title: "Meteora",
    year: 2003,
    deezerId: 1346746,
    genres: ["Nu metal", "Alternatif rock"],
    origin: "Agoura Hills, Kaliforniya, ABD",
    why: "\"Numb\", \"Faint\", \"Breaking the Habit\" — ikinci albüm laneti diye bir şey olmadığının kanıtı.",
    story: [
      "Hybrid Theory'nin gölgesinde bir albüm yapmak yerine grup formülü rafine etti. Meteora adı, Shinoda'nın Yunanistan'daki kayalıkların üstüne kurulu Meteora manastırlarını anlatan bir posterde gördüğü kelimeden geliyor.",
      "Albüm Billboard 200'e 1 numaradan girdi. \"Numb\" grubun en çok dinlenen şarkısı oldu; \"Breaking the Habit\" ise Shinoda'nın beş yıl boyunca üzerinde çalıştığı, Bennington'ın 'hayatımın hikâyesi' dediği şarkıdır. Klip, Japon anime stüdyosu Gonzo tarafından çizildi.",
    ],
    artistInfo:
      "Meteora, Linkin Park'ın en yoğun ve en 'temiz' albümü olarak kabul edilir. \"Numb\", Jay-Z ile yapılan \"Numb/Encore\" mash-up'ı sayesinde 2006'da Grammy kazandı.",
    members: ["Chester Bennington – vokal", "Mike Shinoda – vokal, rap, klavye", "Brad Delson – gitar", "Dave Farrell – bas", "Joe Hahn – turntable, sample", "Rob Bourdon – davul"],
    funFacts: [
      "Kapaktaki grafiti sanatçısı, albüm kitapçığında da eserleri yer alan sokak sanatçısı DELTA.",
      "\"Session\" adlı enstrümantal parça Grammy'ye aday gösterildi.",
      "\"Numb\" yayımlandıktan 20 yıl sonra bile YouTube'da en çok izlenen rock kliplerinden biri.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "chevelle-wonder-whats-next",
    artist: "Chevelle",
    title: "Wonder What's Next",
    year: 2002,
    deezerId: 71683,
    genres: ["Alternatif metal", "Post-grunge"],
    origin: "Grayslake, Illinois, ABD",
    why: "\"The Red\" ve \"Send the Pain Below\" — Breaking Benjamin sevenler için doğal bir sonraki durak.",
    story: [
      "Illinois'li üç kardeşin (Pete, Sam ve Joe Loeffler) ikinci albümü, Rage Against the Machine'in prodüktörü GGGarth Richardson ile kaydedildi. \"The Red\", Pete Loeffler'in öfke kontrolü seansları hakkında yazdığı bir şarkı olarak grubun ilk radyo hiti oldu.",
      "\"Send the Pain Below\" hem Mainstream hem Modern Rock listelerinde 1 numaraya çıktı; albüm platin sertifika aldı. Tool'un ağır ritimleriyle Helmet'in keskin gitarlarını birleştiren ses, Chevelle'i 2000'lerin en istikrarlı hard rock gruplarından biri yaptı.",
    ],
    artistInfo:
      "Chevelle bir aile grubu olarak başladı; basçı Joe Loeffler 2005'te ayrıldı ve yerine kardeşlerin eniştesi Dean Bernardini geçti. Grubun adı babalarının sevdiği Chevrolet Chevelle otomobilinden geliyor.",
    members: ["Pete Loeffler – vokal, gitar", "Joe Loeffler – bas", "Sam Loeffler – davul"],
    funFacts: [
      "Grubun adı, Loeffler kardeşlerin babasının klasik araba tutkusuna bir selam.",
      "\"The Red\" klibinde kalabalık bir öfke kontrolü grup terapisi sahnelenir.",
      "Albüm, Chevelle'in Epic Records'taki ilk kaydıydı ve grubu Ozzfest sahnesine taşıdı.",
    ],
    relatedTo: ["Breaking Benjamin", "Three Days Grace"],
  },
  {
    slug: "seether-karma-and-effect",
    artist: "Seether",
    title: "Karma and Effect",
    year: 2005,
    deezerId: 8015752,
    genres: ["Post-grunge", "Alternatif metal"],
    origin: "Pretoria, Güney Afrika",
    why: "\"Remedy\" ve \"Truth\" — Güney Afrika'dan çıkan en büyük post-grunge grubunun zirvesi.",
    story: [
      "Saron Gas adıyla Güney Afrika'da başlayan grup, ABD'ye taşınırken adını Veruca Salt'ın \"Seether\" şarkısından aldı. Üçüncü albümün orijinal adı 'Catering to Cowards'tı, ancak plak şirketi bu ismi reddetti.",
      "\"Remedy\" Mainstream Rock listesinde 1 numaraya çıktı ve albüm Billboard 200'de Top 10'a girdi. Shaun Morgan'ın Nirvana etkili, kısık vokali ve Bob Marlette'in ağır prodüksiyonu, albümü grubun en tutarlı işi yaptı.",
    ],
    artistInfo:
      "Seether: Shaun Morgan (vokal, gitar), Dale Stewart (bas), John Humphrey (davul) ve bu albümde Pat Callahan (gitar). Morgan, aynı dönemde Evanescence'ın Amy Lee ile ilişkisiyle de gündemdeydi; ikili \"Broken\" düetiyle tanınıyordu.",
    members: ["Shaun Morgan – vokal, gitar", "Pat Callahan – solo gitar", "Dale Stewart – bas", "John Humphrey – davul"],
    funFacts: [
      "Evanescence'ın \"Call Me When You're Sober\" şarkısı Shaun Morgan hakkında yazıldı.",
      "Albümün reddedilen adı 'Catering to Cowards', bugün hâlâ hayranlar arasında kullanılır.",
      "Seether'ın Güney Afrika'daki ilk konserleri, grubun bugün çaldığı arenaların yanında minik pub'lardı.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "halestorm-the-strange-case-of",
    artist: "Halestorm",
    title: "The Strange Case Of...",
    year: 2012,
    deezerId: 1642359,
    genres: ["Hard rock", "Heavy metal"],
    origin: "Red Lion, Pennsylvania, ABD",
    why: "Pretty Reckless'in Momsen'ini seviyorsan Lzzy Hale'in Grammy'li albümünü dinlemelisin.",
    story: [
      "Lzzy Hale 13, kardeşi Arejay 10 yaşındayken 1997'de kurdukları grup, uzun yıllar Pennsylvania barlarında çaldı. İkinci albüm için Howard Benson (Three Days Grace'in de prodüktörü) ile çalıştılar.",
      "Albüm adı Dr. Jekyll ve Mr. Hyde'a gönderme: bir yüzü \"Love Bites (So Do I)\" gibi hızlı metal, diğer yüzü \"Break In\" gibi baladlar. \"Love Bites (So Do I)\" 2013'te Grammy'de En İyi Hard Rock/Metal Performansı ödülünü aldı; bu kategoriyi kazanan ilk kadın vokalli grup oldular.",
    ],
    artistInfo:
      "Halestorm: Lzzy Hale (vokal, gitar), Arejay Hale (davul), Joe Hottinger (gitar) ve Josh Smith (bas). Lzzy Hale, Gibson'ın ilk kadın marka elçisi ve modern hard rock'ın en tanınan seslerinden biri.",
    members: ["Lzzy Hale – vokal, gitar", "Joe Hottinger – gitar", "Josh Smith – bas", "Arejay Hale – davul"],
    funFacts: [
      "Grup Grammy ödülünü alırken Lzzy 'kadın vokalli' değil sadece 'bir rock grubu' olduklarını vurguladı.",
      "\"Freak Like Me\" ve \"I Miss the Misery\" aktif rock radyolarında 1 numaraya çıktı.",
      "Arejay Hale konserlerde dev baget kullanmasıyla ünlü.",
    ],
    relatedTo: ["The Pretty Reckless", "Three Days Grace"],
  },
  {
    slug: "shinedown-the-sound-of-madness",
    artist: "Shinedown",
    title: "The Sound of Madness",
    year: 2008,
    deezerId: 101841,
    genres: ["Hard rock", "Post-grunge"],
    origin: "Jacksonville, Florida, ABD",
    why: "\"Second Chance\" ve başlık şarkısı — Three Days Grace ile rock radyosunun rekorlarını paylaşan grup.",
    story: [
      "Kadro değişikliğinden sonra (Zach Myers ve Eric Bass katıldı) Brent Smith, grubun en iddialı albümünü Green Day'in prodüktörü Rob Cavallo ile kaydetti. \"Second Chance\", Smith'in müzik için ailesini ve şehrini terk etmesini anlatıyor ve Hot 100'de Top 10'a girerek grubu pop dinleyicisine taşıdı.",
      "Albüm, Billboard 200'de iki yıldan uzun süre kaldı ve birden fazla 1 numaralı rock single'ı çıkardı: \"Devour\", \"Sound of Madness\", \"If You Only Knew\", \"The Crow & the Butterfly\". Shinedown sonradan Mainstream Rock listesinde en çok 1 numaraya çıkan grup unvanını aldı.",
    ],
    artistInfo:
      "Shinedown: Brent Smith (vokal), Zach Myers (gitar), Eric Bass (bas) ve Barry Kerch (davul). Grup, 2000'lerin rock radyosunun Three Days Grace ile birlikte en istikrarlı ismi oldu.",
    members: ["Brent Smith – vokal", "Zach Myers – gitar", "Eric Bass – bas", "Barry Kerch – davul"],
    funFacts: [
      "\"Second Chance\"in sözlerindeki Halley kuyruklu yıldızı, hayatta bir kez gelen fırsatlara gönderme.",
      "Albüm Billboard 200'de 120 haftadan fazla kaldı.",
      "Brent Smith bu dönemde ciddi bir yaşam tarzı değişikliğine gitti ve 30 kilodan fazla verdi.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "my-chemical-romance-the-black-parade",
    artist: "My Chemical Romance",
    title: "The Black Parade",
    year: 2006,
    deezerId: 257854,
    genres: ["Emo", "Alternatif rock", "Rock operası"],
    origin: "Newark, New Jersey, ABD",
    why: "Panic! At the Disco'nun teatralliğini seviyorsan, emo kuşağının rock operası burada.",
    story: [
      "Konsept albüm, kanserden ölmek üzere olan 'Hasta'nın hikâyesini anlatır: ölüm ona, çocukken babasıyla izlediği bir geçit töreni şeklinde gelir. Gerard Way bu fikri kendi çocukluk anısından aldı. Grup, Los Angeles'taki perili olduğu söylenen Paramour Malikânesi'nde kaydetti; Mikey Way depresyon nedeniyle malikâneyi terk etti.",
      "Rob Cavallo prodüktörlüğündeki albüm, Queen ve Pink Floyd'dan beslenen bir rock operasıydı. \"Welcome to the Black Parade\" İngiltere'de 1 numaraya çıktı; grup, sahnede siyah bando üniformalarıyla 'The Black Parade' alter egosuna dönüştü. \"Mama\"da Liza Minnelli misafir vokal yapıyor.",
    ],
    artistInfo:
      "My Chemical Romance: Gerard Way (vokal), Ray Toro ve Frank Iero (gitar), Mikey Way (bas) ve Bob Bryar (davul). Way, grubu 11 Eylül saldırılarına tanık olduktan sonra kurdu.",
    members: ["Gerard Way – vokal", "Ray Toro – solo gitar", "Frank Iero – ritim gitar", "Mikey Way – bas", "Bob Bryar – davul"],
    funFacts: [
      "Gerard Way saçlarını albüm için platin sarıya boyadı; bu görüntü bir dönemin sembolü oldu.",
      "Liza Minnelli'nin vokalleri, o New York'tayken telefon üzerinden yönlendirilerek kaydedildi.",
      "\"Teenagers\" Way tarafından metroda, gençlerden korktuğunu fark ettiği bir anda yazıldı.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "fall-out-boy-from-under-the-cork-tree",
    artist: "Fall Out Boy",
    title: "From Under the Cork Tree",
    year: 2005,
    deezerId: 122005,
    genres: ["Pop punk", "Emo pop"],
    origin: "Wilmette, Illinois, ABD",
    why: "Panic! At the Disco'yu keşfeden Pete Wentz'in kendi grubunun çıkış albümü.",
    story: [
      "Chicago'nun banliyölerinden gelen grup, ikinci albümüyle emo'yu MTV'ye taşıdı. Albümün adı, çiçek koklamayı dövüşmeye tercih eden boğa Ferdinand'ın çocuk kitabından geliyor. \"Sugar, We're Goin Down\" Hot 100'de 8 numaraya çıktı; \"Dance, Dance\" onu izledi.",
      "Albüm çıkmadan aylar önce Pete Wentz bir otoparkta ilaç aşırı dozuyla intihar girişiminde bulundu; \"7 Minutes in Heaven (Atavan Halen)\" o geceyi anlatır. Neal Avron prodüktörlüğündeki albüm grubu Grammy'de En Yeni Sanatçı adaylığına taşıdı.",
    ],
    artistInfo:
      "Fall Out Boy: Patrick Stump (vokal, gitar), Pete Wentz (bas, sözler), Joe Trohman (gitar) ve Andy Hurley (davul). Wentz aynı yıl Panic! At the Disco'yu Decaydance etiketine imzalattı.",
    members: ["Patrick Stump – vokal, gitar", "Pete Wentz – bas, sözler", "Joe Trohman – gitar", "Andy Hurley – davul"],
    funFacts: [
      "Sözleri Wentz yazar, melodileri Stump besteler; Stump çoğu zaman sözlerin ne anlama geldiğini bilmeden söyler.",
      "\"Sugar, We're Goin Down\" klibindeki geyik boynuzlu çocuk, grubun en tanınan görsel imgelerinden biri oldu.",
      "Albümün uzun şarkı isimleri, Panic! At the Disco'nun aynı yıl çıkan albümüne doğrudan ilham verdi.",
    ],
    relatedTo: ["Panic! At the Disco"],
  },
  {
    slug: "arctic-monkeys-am",
    artist: "Arctic Monkeys",
    title: "AM",
    year: 2013,
    deezerId: 6899610,
    genres: ["Bağımsız rock", "Alternatif rock", "Psikedelik rock"],
    origin: "Sheffield, İngiltere",
    why: "The Neighbourhood'un gece havasını seviyorsan: Dr. Dre ritimleriyle Black Sabbath riffleri.",
    story: [
      "Alex Turner, beşinci albüm için 'Dr. Dre ritimlerinin üzerinde Black Sabbath çalmak' fikrini kurdu. James Ford prodüktörlüğünde Los Angeles ve Joshua Tree çölündeki Rancho de la Luna'da kaydedilen AM, R&B ve hip-hop'un ağır tempolarını rock'la birleştirdi.",
      "\"Do I Wanna Know?\", \"R U Mine?\" ve \"Why'd You Only Call Me When You're High?\" grubu ABD'de nihayet büyük bir isim yaptı. Queens of the Stone Age'in Josh Homme'u iki şarkıda geri vokal yapıyor. Kapaktaki ses dalgası grubun en ikonik görsellerinden biri oldu.",
    ],
    artistInfo:
      "Arctic Monkeys: Alex Turner (vokal, gitar), Jamie Cook (gitar), Nick O'Malley (bas) ve Matt Helders (davul). Albüm adı Velvet Underground'un VU albümüne gönderme.",
    members: ["Alex Turner – vokal, gitar", "Jamie Cook – gitar", "Nick O'Malley – bas, geri vokal", "Matt Helders – davul, geri vokal"],
    funFacts: [
      "\"Do I Wanna Know?\" grubun Billboard Hot 100'e giren ilk şarkısı oldu.",
      "Turner sözlerinde Aaliyah ve Outkast'i ilham kaynağı olarak gösterdi.",
      "AM, İngiltere'de yılın en çok satan vinil albümü oldu.",
    ],
    relatedTo: ["The Neighbourhood"],
  },
  {
    slug: "arctic-monkeys-whatever-people-say-i-am",
    artist: "Arctic Monkeys",
    title: "Whatever People Say I Am, That's What I'm Not",
    year: 2006,
    deezerId: 401340,
    genres: ["Bağımsız rock", "Garaj rock", "Post-punk canlanması"],
    origin: "Sheffield, İngiltere",
    why: "İngiliz tarihinin en hızlı satan çıkış albümü; Sheffield gecelerinin gözlem defteri.",
    story: [
      "Demolarını ücretsiz dağıtan ve hayranlarının MySpace'te paylaşmasıyla büyüyen grup, henüz albüm çıkarmadan konserlerinde tüm şarkıların eşlik edildiğini görüyordu. Albüm ilk haftasında 363.000'den fazla satarak İngiltere'de bir çıkış albümü rekoru kırdı.",
      "Alex Turner'ın taksi kuyrukları, kulüp fedaileri ve gece sonu pişmanlıkları hakkındaki gözlemci sözleri, albümü bir kuşağın günlüğü yaptı. \"I Bet You Look Good on the Dancefloor\" ve \"When the Sun Goes Down\" İngiltere'de 1 numaraya çıktı; albüm Mercury Ödülü'nü kazandı.",
    ],
    artistInfo:
      "Andy Nicholson'ın basta yer aldığı tek Arctic Monkeys albümü. Albümün adı, Alan Sillitoe'nun 'Saturday Night and Sunday Morning' romanının film uyarlamasındaki bir replikten geliyor.",
    members: ["Alex Turner – vokal, gitar", "Jamie Cook – gitar", "Andy Nicholson – bas", "Matt Helders – davul, geri vokal"],
    funFacts: [
      "Kapaktaki sigara içen adam grubun arkadaşı Chris McClure; kapak yüzünden 'sigarayı özendirme' tartışması çıktı.",
      "Grup üyeleri albüm çıktığında 19-20 yaşındaydı ve gitar çalmayı sadece dört yıl önce öğrenmişlerdi.",
      "Albüm çıkmadan önce hayranlar, demoları 'Beneath the Boardwalk' adıyla derleyip paylaşıyordu.",
    ],
    relatedTo: ["The Neighbourhood"],
  },
  {
    slug: "the-shins-wincing-the-night-away",
    artist: "The Shins",
    title: "Wincing the Night Away",
    year: 2007,
    deezerId: 185286352,
    genres: ["Bağımsız rock", "Bağımsız pop"],
    origin: "Albuquerque, New Mexico, ABD",
    why: "Broken Bells'in sesi James Mercer'ın kendi grubuyla yaptığı en büyük albüm.",
    story: [
      "Garden State filmindeki 'The Shins hayatını değiştirecek' repliğinden sonra grup indie dünyasının en tanınan ismi olmuştu. Üçüncü albüm için Mercer, uykusuzluk çektiği gecelerde yazdı; albüm adı Sam Cooke'un \"Twistin' the Night Away\"ine bir kelime oyunu.",
      "\"Phantom Limb\" ve \"Australia\" ile albüm Billboard 200'e 2 numaradan girdi — bağımsız Sub Pop etiketinin o güne kadarki en yüksek açılışı. Grammy'de En İyi Alternatif Albüm adaylığı aldı. Mercer'ın melodi anlayışı, üç yıl sonra Broken Bells'te Danger Mouse'la buluşacaktı.",
    ],
    artistInfo:
      "The Shins, James Mercer'ın 1996'da Albuquerque'de kurduğu ve daha sonra Portland'a taşıdığı grup. Mercer 2009'da kadroyu tamamen değiştirdi; grup fiilen onun projesi hâline geldi.",
    members: ["James Mercer – vokal, gitar", "Marty Crandall – klavye", "Dave Hernandez – bas, gitar", "Jesse Sandoval – davul"],
    funFacts: [
      "\"Phantom Limb\", bir kasabada dışlanan iki genç kızın hikâyesini anlatır.",
      "Sub Pop, albümün başarısıyla ilk kez Billboard Top 5'e giren bir plak yayımladı.",
      "Mercer albümün bazı bölümlerini kendi evinin bodrumunda kaydetti.",
    ],
    relatedTo: ["Broken Bells"],
  },
  {
    slug: "gorillaz-demon-days",
    artist: "Gorillaz",
    title: "Demon Days",
    year: 2005,
    deezerId: 301752,
    genres: ["Alternatif hip hop", "Sanat pop'u", "Trip hop"],
    origin: "Londra, İngiltere",
    why: "Danger Mouse'un Broken Bells'ten önceki başyapıtı; kapağı Beatles'ın Let It Be'sine selam veriyor.",
    story: [
      "Blur'un Damon Albarn'ı ve çizer Jamie Hewlett'in sanal grubu ikinci albüm için Danger Mouse'u prodüktör seçti — o dönem sadece yasadışı 'Grey Album' mash-up'ıyla tanınan genç bir isimdi. Albarn'ın Çin'de yaptığı bir tren yolculuğu albümün karanlık, kıyamet sonrası atmosferini şekillendirdi.",
      "\"Feel Good Inc.\" (De La Soul ile, Grammy ödüllü), \"DARE\" (Shaun Ryder ile İngiltere 1 numarası), \"Dirty Harry\" ve \"El Mañana\" ile albüm dünya çapında altı milyondan fazla sattı. Dennis Hopper'ın anlatıcı olduğu \"Fire Coming Out of the Monkey's Head\" ve Ike Turner'ın piyano çaldığı \"Every Planet We Reach Is Dead\" gibi sürpriz misafirler albümün konsept zenginliğini gösteriyor.",
    ],
    artistInfo:
      "Gorillaz, dört çizgi karakterden (2-D, Murdoc, Noodle, Russel) oluşan sanal bir grup; müziği Damon Albarn ve dönüşümlü misafirler yapıyor. Demon Days, Danger Mouse'u dünyanın en aranan prodüktörlerinden biri hâline getirdi.",
    members: ["Damon Albarn – vokal, klavye, prodüksiyon", "Jamie Hewlett – görsel dünya", "Danger Mouse – prodüksiyon", "Misafirler: De La Soul, Shaun Ryder, Neneh Cherry, MF DOOM, Dennis Hopper"],
    funFacts: [
      "Kapak, Beatles'ın Let It Be albümünün dörtlü portre düzenini birebir taklit eder.",
      "\"Feel Good Inc.\" Grammy'de En İyi Pop İş Birliği ödülünü kazandı.",
      "Albümün sonundaki koro, Londra Toplum Gospel Korosu tarafından söylenir.",
    ],
    relatedTo: ["Broken Bells", "The Beatles"],
  },
  {
    slug: "twenty-one-pilots-blurryface",
    artist: "Twenty One Pilots",
    title: "Blurryface",
    year: 2015,
    deezerId: 10236282,
    genres: ["Alternatif", "Pop rap", "Elektro-pop"],
    origin: "Columbus, Ohio, ABD",
    why: "Panic! ve Imagine Dragons dinleyicilerinin bir sonraki büyük keşfi: \"Stressed Out\" ve \"Ride\".",
    story: [
      "Tyler Joseph, albüm için 'Blurryface' adlı bir karakter yarattı: güvensizliklerini temsil eden, boynu ve elleri siyah boyalı bir figür. Albüm boyunca bu karakterle mücadelesi anlatılır. Josh Dun'ın davulları ve Joseph'in rap, ukulele ve synth karışımı, türü tanımlanamayan bir ses yarattı.",
      "\"Stressed Out\" Hot 100'de 2 numaraya çıktı ve Grammy kazandı — ikili ödülü, yıllar önce yaptıkları bir anlaşmaya sadık kalarak iç çamaşırlarıyla aldı. Blurryface, RIAA tarihinde her şarkısı en az altın sertifika alan ilk albüm oldu.",
    ],
    artistInfo:
      "Twenty One Pilots, Tyler Joseph (vokal, klavye, bas, ukulele) ve Josh Dun (davul, trompet) ikilisi. Grup adı Arthur Miller'ın 'All My Sons' oyunundan geliyor.",
    members: ["Tyler Joseph – vokal, klavye, bas, ukulele", "Josh Dun – davul, perküsyon"],
    funFacts: [
      "\"Tear in My Heart\" Joseph'in eşi Jenna için yazıldı.",
      "Albümdeki her şarkı RIAA tarafından en az altın sertifika aldı — bu, tarihte bir ilk.",
      "Blurryface karakterinin siyah boyası, Joseph'in konserlerde de kullandığı bir sahne imgesi oldu.",
    ],
    relatedTo: ["Panic! At the Disco", "Imagine Dragons"],
  },
  {
    slug: "bring-me-the-horizon-thats-the-spirit",
    artist: "Bring Me the Horizon",
    title: "That's the Spirit",
    year: 2015,
    deezerId: 11130386,
    genres: ["Alternatif rock", "Elektronik rock", "Alternatif metal"],
    origin: "Sheffield, İngiltere",
    why: "\"Throne\", \"Drown\" ve \"Happy Song\" — metalcore'dan arena rock'a dönüşün albümü.",
    story: [
      "Deathcore ile başlayan Sheffield'lı grup, beşinci albümde tamamen yeni bir yöne gitti: keyboardcu Jordan Fish'in synth'leri, Oli Sykes'ın temiz vokali ve stadyum nakaratları. Albüm Yunanistan'ın Santorini adasında, grup üyelerinin kendi prodüksiyonuyla kaydedildi.",
      "\"Drown\", \"Throne\" ve \"Happy Song\" ile That's the Spirit hem İngiltere'de hem ABD'de 2 numaraya çıktı. Albüm depresyonu alaycı bir 'pozitiflikle' ele alır; kapaktaki şemsiye logosu bu ironinin sembolü.",
    ],
    artistInfo:
      "Bring Me the Horizon: Oli Sykes (vokal), Lee Malia (gitar), Matt Kean (bas), Matt Nicholls (davul) ve Jordan Fish (klavye). Sykes'ın 2013'te ketamin bağımlılığından kurtulması, grubun sonraki albümlerinin arka planını oluşturur.",
    members: ["Oli Sykes – vokal", "Lee Malia – gitar", "Matt Kean – bas", "Matt Nicholls – davul", "Jordan Fish – klavye, programlama"],
    funFacts: [
      "Albüm Santorini'de deniz manzaralı bir stüdyoda kaydedildi.",
      "\"Happy Song\"un açılışındaki amigo kız nakaratı, depresyonu neşeli bir slogan gibi söyleme ironisini taşır.",
      "Şemsiye logosu, 'That's the spirit!' deyiminin sahte iyimserliğini simgeliyor.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "paramore-riot",
    artist: "Paramore",
    title: "Riot!",
    year: 2007,
    deezerId: 356913,
    genres: ["Pop punk", "Emo pop", "Alternatif rock"],
    origin: "Franklin, Tennessee, ABD",
    why: "Breaking Benjamin'in prodüktörü David Bendeth'in elinden çıkan pop-punk klasiği.",
    story: [
      "Tennessee'li gençlerin ikinci albümü, Breaking Benjamin'in Phobia'sını da üreten David Bendeth ile New Jersey'de kaydedildi. Bendeth grubun sesini keskinleştirdi; Hayley Williams'ın vokali türün en güçlü seslerinden biri olarak öne çıktı.",
      "\"Misery Business\" grubun ilk büyük hiti oldu; \"crushcrushcrush\" ve \"That's What You Get\" onu izledi. Albüm platin sertifika aldı ve grup Grammy'de En Yeni Sanatçı adaylığı kazandı. 'Riot' kelimesi, 'ani ve kontrolsüz bir duygu patlaması' anlamıyla seçildi.",
    ],
    artistInfo:
      "Paramore, 2004'te Franklin, Tennessee'de kuruldu: Hayley Williams (vokal), Josh Farro (gitar), Zac Farro (davul) ve Jeremy Davis (bas). Grup daha sonra birçok kadro değişikliği geçirdi ancak Williams merkezde kaldı.",
    members: ["Hayley Williams – vokal", "Josh Farro – solo gitar, geri vokal", "Jeremy Davis – bas", "Zac Farro – davul"],
    funFacts: [
      "Williams, sözleri nedeniyle \"Misery Business\"i 2018-2022 arasında konserlerde çalmayı bıraktı.",
      "Kapakta 'riot' kelimesi yüzlerce kez el yazısıyla tekrarlanır.",
      "Albümün turnesinde grup Twilight soundtrack'i için \"Decode\"u yazdı.",
    ],
    relatedTo: ["Breaking Benjamin", "Panic! At the Disco", "The Pretty Reckless"],
  },
  {
    slug: "papa-roach-infest",
    artist: "Papa Roach",
    title: "Infest",
    year: 2000,
    deezerId: 84923722,
    genres: ["Nu metal", "Rap rock"],
    origin: "Vacaville, Kaliforniya, ABD",
    why: "\"Last Resort\" — Three Days Grace'ten önce aynı öfkeyi radyoya taşıyan albüm.",
    story: [
      "Kaliforniya'nın küçük kasabası Vacaville'den gelen grup, bağımsız kayıtlardan sonra DreamWorks ile anlaştı. \"Last Resort\", Jacoby Shaddix'in ev arkadaşının intihar girişimi üzerine yazıldı ve 2000 yılının en çok çalınan rock şarkılarından biri oldu.",
      "\"Broken Home\" ve \"Between Angels and Insects\" ile albüm üç kez platin sertifika aldı. Rap ve rock'ı birleştiren sesiyle Infest, nu metal dalgasının en başarılı kayıtlarından biri hâline geldi ve grup Grammy'ye aday gösterildi.",
    ],
    artistInfo:
      "Papa Roach: Jacoby Shaddix (vokal), Jerry Horton (gitar), Tobin Esperance (bas) ve Dave Buckner (davul). Grubun adı Shaddix'in üvey dedesi Howard William 'Papa' Roatch'tan geliyor.",
    members: ["Jacoby Shaddix – vokal", "Jerry Horton – gitar", "Tobin Esperance – bas", "Dave Buckner – davul"],
    funFacts: [
      "\"Last Resort\"un ilk dizesi 'Cut my life into pieces' yıllar sonra internet meme'i hâline geldi.",
      "Grubun adı bir hamamböceğiyle değil, Shaddix'in dedesinin lakabıyla ilgili.",
      "Albüm çıkmadan önce grup, Vacaville'de kendi kasetlerini konserlerde elden satıyordu.",
    ],
    relatedTo: ["Three Days Grace"],
  },
  {
    slug: "evanescence-fallen",
    artist: "Evanescence",
    title: "Fallen",
    year: 2003,
    deezerId: 8015598,
    genres: ["Gotik metal", "Alternatif metal", "Nu metal"],
    origin: "Little Rock, Arkansas, ABD",
    why: "\"Bring Me to Life\" ve \"My Immortal\" — Pretty Reckless öncesi kadın vokalli rock'ın dönüm noktası.",
    story: [
      "Amy Lee ve Ben Moody'nin Arkansas'ta gençken kurduğu grup, Fallen ile bir gecede dünya çapında ünlü oldu. Plak şirketi, \"Bring Me to Life\"a erkek vokal eklenmesinde ısrar etti; 12 Stones'un Paul McCoy'unun rap bölümü böyle doğdu. Şarkı Daredevil filmiyle yayıldı.",
      "Albüm 17 milyondan fazla sattı ve grup 2004'te Grammy'de En Yeni Sanatçı ve En İyi Hard Rock Performansı ödüllerini kazandı. Kurucu ortak Ben Moody, albüm turnesinin ortasında gruptan ayrıldı; Amy Lee grubun tek kalıcı üyesi oldu.",
    ],
    artistInfo:
      "Evanescence'ın çıkış kadrosu: Amy Lee (vokal, piyano), Ben Moody (gitar), John LeCompt (gitar), Will Boyd (bas) ve Rocky Gray (davul). Lee'nin klasik müzik eğitimi, grubun gotik piyano ve gitar karışımının temeli.",
    members: ["Amy Lee – vokal, piyano", "Ben Moody – gitar", "John LeCompt – gitar", "Will Boyd – bas", "Rocky Gray – davul"],
    funFacts: [
      "Plak şirketi grubu başta Hristiyan rock pazarına yönlendirdi; grup bu etiketi açıkça reddetti.",
      "\"My Immortal\"ın albüm versiyonu ile radyoda çalınan 'band version' farklı kayıtlar.",
      "Amy Lee, Seether'ın Shaun Morgan'ıyla ilişkisini \"Call Me When You're Sober\"da anlattı.",
    ],
    relatedTo: ["The Pretty Reckless", "Breaking Benjamin"],
  },
  {
    slug: "royal-blood-royal-blood",
    artist: "Royal Blood",
    title: "Royal Blood",
    year: 2014,
    deezerId: 8310464,
    genres: ["Hard rock", "Blues rock", "Garaj rock"],
    origin: "Brighton, İngiltere",
    why: "Sadece bas ve davulla stadyum dolduran ikili — Arctic Monkeys'in kefil olduğu çıkış.",
    story: [
      "Mike Kerr'in bas gitarını efektlerle gitar gibi çalması ve Ben Thatcher'ın gürültülü davulu, iki kişilik bir gruptan Led Zeppelin büyüklüğünde bir ses çıkardı. Arctic Monkeys'in Matt Helders 2013 Glastonbury'de sahneye Royal Blood tişörtüyle çıktı — grup henüz tek bir şarkı yayımlamamıştı.",
      "Çıkış albümü İngiltere'de 1 numaraya girdi ve üç yılın en hızlı satan İngiliz rock çıkışı oldu. \"Figure It Out\", \"Little Monster\" ve \"Out of the Black\" grubu Brit Ödülleri'nde En İyi İngiliz Grubu yaptı; Jimmy Page albümü 'yılların en iyi rock kaydı' diye övdü.",
    ],
    artistInfo:
      "Royal Blood, Brighton'dan Mike Kerr (bas, vokal) ve Ben Thatcher (davul) ikilisi. Kerr, bas sesini bölerek aynı anda bas ve gitar frekanslarında çalıyor; grubun 'gitaristi yok' gizemi buradan geliyor.",
    members: ["Mike Kerr – bas, vokal", "Ben Thatcher – davul"],
    funFacts: [
      "Grup Brit Ödülleri'nde 2015'te En İyi İngiliz Grubu ödülünü çıkış albümüyle kazandı.",
      "Led Zeppelin'in Jimmy Page'i grubu bizzat konserde izledi ve övdü.",
      "Kerr'ın pedal düzeni yıllarca gizli tutuldu; grup bunun 'sihrin bir parçası' olduğunu söylüyor.",
    ],
    relatedTo: ["The Pretty Reckless", "Arctic Monkeys"],
  },
  {
    slug: "nothing-but-thieves-nothing-but-thieves",
    artist: "Nothing But Thieves",
    title: "Nothing But Thieves",
    year: 2015,
    deezerId: 16576221,
    genres: ["Alternatif rock", "Bağımsız rock"],
    origin: "Southend-on-Sea, İngiltere",
    why: "Conor Mason'ın falsetto vokali ve \"Trip Switch\" — Imagine Dragons ile Muse arasında bir köprü.",
    story: [
      "Essex'ten gelen beşli, Conor Mason'ın Jeff Buckley ve Matt Bellamy'ye benzetilen vokaliyle dikkat çekti. Çıkış albümleri İngiltere'de Top 10'a girdi; \"Trip Switch\" ise ABD'de Billboard Alternative listesinde 1 numaraya çıktı — bir İngiliz grubunun çıkış single'ı için nadir bir başarı.",
      "Muse grubu, Drones turnesinde açılış grubu olarak bizzat seçti; Twenty One Pilots ile de turneye çıktılar. \"Wake Up Call\", \"Itch\" ve \"Ban All the Music\" albümün gitar ağırlıklı ve dinamik yüzünü, \"Lover, Please Stay\" ise Mason'ın kırılgan tarafını gösteriyor.",
    ],
    artistInfo:
      "Nothing But Thieves: Conor Mason (vokal), Joe Langridge-Brown ve Dominic Craik (gitar), Philip Blake (bas) ve James Price (davul). Grup 2012'de Southend-on-Sea'de kuruldu.",
    members: ["Conor Mason – vokal, gitar", "Joe Langridge-Brown – gitar", "Dominic Craik – gitar, klavye", "Philip Blake – bas", "James Price – davul"],
    funFacts: [
      "\"Trip Switch\" ABD Alternative listesinde 1 numaraya çıkan ilk İngiliz çıkış single'larından biri oldu.",
      "Muse, grubu Drones turnesine bizzat davet etti.",
      "Conor Mason'ın vokal aralığı, albümde \"Lover, Please Stay\"deki fısıltıdan \"Itch\"teki çığlığa uzanır.",
    ],
    relatedTo: ["Imagine Dragons", "Muse"],
  },
  {
    slug: "highly-suspect-mister-asylum",
    artist: "Highly Suspect",
    title: "Mister Asylum",
    year: 2015,
    deezerId: 10802828,
    genres: ["Alternatif rock", "Blues rock", "Grunge"],
    origin: "Cape Cod, Massachusetts, ABD",
    why: "\"Lydia\" ve \"Bloodfeather\" — Grammy adayı bir çıkış; Pretty Reckless'in bluesy karanlığını seviyorsan.",
    story: [
      "Cape Cod barlarında cover grubu olarak başlayan üçlü (Johnny Stevens ve ikiz kardeşler Rich ve Ryan Meyer) Brooklyn'e taşınıp kendi şarkılarını yazmaya başladı. Prodüktör Joel Hamilton ile Brooklyn'de kaydedilen Mister Asylum, ham ve kirli bir blues-grunge kaydı.",
      "\"Lydia\", Stevens'ın eski sevgilisi için yazdığı çıkış single'ı olarak Grammy'de En İyi Rock Şarkısı adaylığı aldı; albüm de En İyi Rock Albümü kategorisinde aday gösterildi. Bir çıkış albümü için bu çift adaylık nadir görülen bir başarıydı.",
    ],
    artistInfo:
      "Highly Suspect: Johnny Stevens (vokal, gitar), Rich Meyer (bas) ve Ryan Meyer (davul). Grup, 300 Entertainment etiketiyle çalışan ilk rock gruplarından biri.",
    members: ["Johnny Stevens – vokal, gitar", "Rich Meyer – bas, geri vokal", "Ryan Meyer – davul"],
    funFacts: [
      "Grup yıllarca Cape Cod'daki barlarda Sublime ve Red Hot Chili Peppers cover'ları çalarak geçindi.",
      "\"Lydia\" klibinde bir kadın vücuduna projeksiyonla yansıtılan şarkı sözleri kullanıldı.",
      "Rich ve Ryan Meyer ikiz kardeşler.",
    ],
    relatedTo: ["The Pretty Reckless", "Three Days Grace"],
  },
  {
    slug: "the-black-keys-el-camino",
    artist: "The Black Keys",
    title: "El Camino",
    year: 2011,
    deezerId: 1376944,
    genres: ["Garaj rock", "Blues rock"],
    origin: "Akron, Ohio, ABD",
    why: "Danger Mouse'un ortak prodüktörlüğünde \"Lonely Boy\" ve \"Gold on the Ceiling\" — üç Grammy'li albüm.",
    story: [
      "Dan Auerbach ve Patrick Carney, Broken Bells'in Danger Mouse'u ile Nashville'deki Easy Eye Sound stüdyosunda hızlı, dans edilebilir bir rock albümü yapmaya karar verdi. Brothers'ın ağır blues'undan farklı olarak El Camino glam ve garage rock'a yaslanıyor.",
      "\"Lonely Boy\" klibinde dans eden tek adam (Derrick Tuggle) viral oldu; şarkı Grammy'de En İyi Rock Performansı ve En İyi Rock Şarkısı ödüllerini aldı, albüm de En İyi Rock Albümü seçildi. Kapaktaki minivan bir El Camino değil — grubun ilk turnelerinde kullandığı Plymouth Grand Voyager'a benzeyen bir şaka.",
    ],
    artistInfo:
      "The Black Keys, Akron'lu ikili Dan Auerbach (vokal, gitar) ve Patrick Carney (davul). Danger Mouse ile 2008'den itibaren çalışan grup, El Camino ile stadyum boyutuna ulaştı.",
    members: ["Dan Auerbach – vokal, gitar", "Patrick Carney – davul", "Danger Mouse – ortak prodüksiyon, klavye"],
    funFacts: [
      "Kapaktaki araç bir El Camino değil, bir Chrysler minivan — grubun bilinçli bir şakası.",
      "\"Lonely Boy\" klibi tek çekimde, tek bir dansçıyla çekildi ve viral oldu.",
      "Albüm 2013 Grammy Ödülleri'nde üç ödül kazandı.",
    ],
    relatedTo: ["Broken Bells"],
  },
  {
    slug: "bastille-bad-blood",
    artist: "Bastille",
    title: "Bad Blood",
    year: 2013,
    deezerId: 320446167,
    genres: ["Bağımsız pop", "Synth-pop", "Alternatif"],
    origin: "Londra, İngiltere",
    why: "\"Pompeii\" — Imagine Dragons'ın stadyum pop'unu seviyorsan İngiliz karşılığı bu.",
    story: [
      "Dan Smith'in solo projesi olarak başlayan Bastille, adını Smith'in doğum günü olan 14 Temmuz'dan (Bastille Günü) aldı. Çıkış albümü İngiltere'de 1 numaraya girdi ve grup Brit Ödülleri'nde En İyi Çıkış ödülünü aldı.",
      "\"Pompeii\", volkanik felaketten sonra birbirine bakan iki insanın hikâyesi olarak ABD'de Top 5'e girdi. \"Things We Lost in the Fire\", \"Flaws\" ve Twin Peaks'e gönderme yapan \"Laura Palmer\" albümün sinematik, koro ağırlıklı sesini tamamlıyor.",
    ],
    artistInfo:
      "Bastille: Dan Smith (vokal, klavye), Kyle Simmons (klavye), Will Farquarson (bas, gitar) ve Chris 'Woody' Wood (davul). Smith, popüler kültür ve film referanslarıyla dolu sözleriyle tanınır.",
    members: ["Dan Smith – vokal, klavye", "Kyle Simmons – klavye, geri vokal", "Will Farquarson – bas, gitar", "Chris Wood – davul"],
    funFacts: [
      "\"Pompeii\"deki 'eh-eh-oh' korosu, tek bir vokalin onlarca kez üst üste kaydedilmesiyle yapıldı.",
      "\"Laura Palmer\" doğrudan David Lynch'in Twin Peaks dizisine gönderme.",
      "Dan Smith sahnede şarkı söylerken hâlâ utangaç olduğunu ve yıllarca kameralara bakamadığını söylüyor.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "green-day-american-idiot",
    artist: "Green Day",
    title: "American Idiot",
    year: 2004,
    deezerId: 90799,
    genres: ["Punk rock", "Rock operası", "Alternatif rock"],
    origin: "Berkeley, Kaliforniya, ABD",
    why: "Panic!'in teatralliğiyle Three Days Grace'in öfkesini birleştiren punk rock operası.",
    story: [
      "Grup 'Cigarettes and Valentines' adlı bir albümü neredeyse bitirmişti ki master kayıtlar stüdyodan çalındı. Yeniden kaydetmek yerine sıfırdan başladılar; sonuç, Bush dönemi Amerika'sında 'Banliyönün İsası' karakterinin hikâyesini anlatan bir rock operası oldu.",
      "Rob Cavallo prodüktörlüğündeki albüm, dokuz dakikalık iki süit (\"Jesus of Suburbia\" ve \"Homecoming\") içeriyor. Grammy'de En İyi Rock Albümü ödülünü aldı; \"Boulevard of Broken Dreams\" Yılın Kaydı seçildi. Albüm 2010'da Broadway müzikaline dönüştü.",
    ],
    artistInfo:
      "Green Day: Billie Joe Armstrong (vokal, gitar), Mike Dirnt (bas) ve Tré Cool (davul). 1994'te Dookie ile punk'ı ana akıma taşıyan grup, on yıl sonra American Idiot ile ikinci bir zirveye ulaştı.",
    members: ["Billie Joe Armstrong – vokal, gitar", "Mike Dirnt – bas, geri vokal", "Tré Cool – davul"],
    funFacts: [
      "Çalınan 'Cigarettes and Valentines' kayıtları hiçbir zaman bulunmadı.",
      "Broadway uyarlaması iki Tony Ödülü kazandı.",
      "Kapaktaki kalp şeklindeki el bombası, grubun sonraki turnelerinin de sembolü oldu.",
    ],
    relatedTo: ["Panic! At the Disco", "Three Days Grace"],
  },
  {
    slug: "the-killers-hot-fuss",
    artist: "The Killers",
    title: "Hot Fuss",
    year: 2004,
    deezerId: 164869492,
    genres: ["Bağımsız rock", "New wave", "Post-punk canlanması"],
    origin: "Las Vegas, Nevada, ABD",
    why: "Imagine Dragons ve Panic!'ten önce Las Vegas'tan çıkan büyük grup; \"Mr. Brightside\"ın albümü.",
    story: [
      "Bir otelde komi olarak çalışan Brandon Flowers, gazete ilanıyla gitarist Dave Keuning'i buldu; ilk yazdıkları şarkı \"Mr. Brightside\"dı. Grup ABD'de ilgi görmeyince İngiltere'de bağımsız bir etiketle anlaştı ve önce orada patladı.",
      "\"Somebody Told Me\", \"Mr. Brightside\", \"All These Things That I've Done\" ve \"Smile Like You Mean It\" ile albüm yedi milyondan fazla sattı. \"Mr. Brightside\" İngiltere listelerinde tarihte en uzun süre kalan şarkı oldu; yayımlanmasından yirmi yıl sonra hâlâ Top 100'de.",
    ],
    artistInfo:
      "The Killers: Brandon Flowers (vokal, klavye), Dave Keuning (gitar), Mark Stoermer (bas) ve Ronnie Vannucci Jr. (davul). Grup adı, New Order'ın \"Crystal\" klibindeki hayali grubun davul setinden alındı.",
    members: ["Brandon Flowers – vokal, klavye", "Dave Keuning – gitar", "Mark Stoermer – bas", "Ronnie Vannucci Jr. – davul"],
    funFacts: [
      "\"Mr. Brightside\" Flowers'ın aldatıldığını öğrendiği geceyi anlatır ve grubun yazdığı ilk şarkıdır.",
      "Grup adı New Order'ın \"Crystal\" klibinde görülen sahte bir grubun adından geliyor.",
      "Flowers albüm çıktığında Las Vegas'taki Gold Coast Hotel'de komi olarak çalışıyordu.",
    ],
    relatedTo: ["Imagine Dragons", "Panic! At the Disco"],
  },
  {
    slug: "muse-absolution",
    artist: "Muse",
    title: "Absolution",
    year: 2003,
    deezerId: 511257691,
    genres: ["Alternatif rock", "Progresif rock", "Uzay rock"],
    origin: "Teignmouth, İngiltere",
    why: "\"Time Is Running Out\" ve \"Hysteria\" — Imagine Dragons'ın stadyum rock'ının İngiliz atası.",
    story: [
      "Irak Savaşı'nın arifesinde yazılan Absolution, kıyamet ve kurtuluş temalarıyla Muse'un en karanlık ve en iddialı albümüdür. Rich Costey prodüktörlüğünde kaydedilen albüm, Matt Bellamy'nin Rachmaninoff etkili piyanosunu ve Chris Wolstenholme'un \"Hysteria\"daki efsanevi bas hattını içeriyor.",
      "\"Time Is Running Out\" grubun İngiltere'de ilk Top 10 hiti oldu; albüm İngiltere'de 1 numaraya çıktı ve Muse'u ABD'de de tanıttı. Kapak, Pink Floyd'un kapaklarını tasarlayan Storm Thorgerson'a ait.",
    ],
    artistInfo:
      "Muse, Devon'daki Teignmouth kasabasından üç okul arkadaşı: Matt Bellamy (vokal, gitar, piyano), Chris Wolstenholme (bas) ve Dominic Howard (davul). Absolution ile grup kulüplerden arenalara geçti.",
    members: ["Matt Bellamy – vokal, gitar, piyano", "Chris Wolstenholme – bas, geri vokal", "Dominic Howard – davul"],
    funFacts: [
      "\"Hysteria\"nın bas hattı, birçok ankette 'tüm zamanların en iyi bas hatları' arasında gösteriliyor.",
      "\"Butterflies and Hurricanes\"deki piyano bölümü Rachmaninoff'tan ilham alıyor.",
      "Kapağı tasarlayan Storm Thorgerson, Pink Floyd'un Dark Side of the Moon'unun da tasarımcısı.",
    ],
    relatedTo: ["Imagine Dragons"],
  },
  {
    slug: "foo-fighters-the-colour-and-the-shape",
    artist: "Foo Fighters",
    title: "The Colour and the Shape",
    year: 1997,
    deezerId: 8247832,
    genres: ["Alternatif rock", "Post-grunge"],
    origin: "Seattle, Washington, ABD",
    why: "\"Everlong\" ve \"My Hero\" — post-grunge'ın kurucu metni; Three Days Grace'in kökleri burada.",
    story: [
      "Nirvana'nın ardından Dave Grohl ilk Foo Fighters albümünü tek başına kaydetmişti; ikinci albüm bir 'grup' albümü olacaktı. Ancak Pixies prodüktörü Gil Norton ile yapılan kayıtlar sırasında Grohl, davulcu William Goldsmith'in partilerinin çoğunu gizlice yeniden kaydetti; Goldsmith gruptan ayrıldı.",
      "Grohl'un boşanmasının izlerini taşıyan albüm, \"Everlong\", \"My Hero\", \"Monkey Wrench\" ve \"Walking After You\" ile Foo Fighters'ın en çok satan albümü oldu. \"Everlong\", David Letterman'ın en sevdiği şarkı olarak da tarihe geçti: kalp ameliyatından dönüşünde Foo Fighters turnesini iptal edip programda bu şarkıyı çaldı.",
    ],
    artistInfo:
      "Bu albümdeki kadro: Dave Grohl (vokal, gitar, davul), Nate Mendel (bas), Pat Smear (gitar) ve kısmen William Goldsmith (davul). Albümden sonra Taylor Hawkins davula geçti.",
    members: ["Dave Grohl – vokal, gitar, davul", "Pat Smear – gitar", "Nate Mendel – bas", "William Goldsmith – davul (bazı parçalar)"],
    funFacts: [
      "\"Everlong\", Grohl'un ilk Foo Fighters albümünün turnesinde yaşadığı yeni bir aşkın şarkısı.",
      "Albüm, bir terapi seansı yapısında sıralandı: açılış parçası \"Doll\" bir 'giriş', kapanış \"New Way Home\" bir 'çıkış'.",
      "Grohl, davul partilerini yeniden kaydettiğini Goldsmith'e söylemedi; olay yıllarca konuşuldu.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "skillet-awake",
    artist: "Skillet",
    title: "Awake",
    year: 2009,
    deezerId: 383513,
    genres: ["Hard rock", "Hristiyan rock", "Alternatif metal"],
    origin: "Memphis, Tennessee, ABD",
    why: "\"Monster\", \"Hero\", \"Awake and Alive\" — Three Days Grace'in prodüktörü Howard Benson'ın elinden.",
    story: [
      "Three Days Grace'in One-X ve Life Starts Now'ını üreten Howard Benson ile kaydedilen Awake, Skillet'ı Hristiyan rock sahnesinden ana akım rock radyosuna taşıdı. \"Monster\", ABD'de en çok satan rock şarkılarından biri hâline geldi ve beş kez platin sertifika aldı.",
      "\"Hero\" ve \"Awake and Alive\" ile albüm çift platin oldu; Grammy'de En İyi Rock/Rap Gospel Albümü adaylığı aldı. Yaylılar ve synth'lerle harmanlanmış ağır gitarlar, Skillet'ı 'sinematik hard rock' etiketiyle tanımlanan bir sese taşıdı.",
    ],
    artistInfo:
      "Skillet: John Cooper (vokal, bas), Korey Cooper (gitar, klavye — John'un eşi), Ben Kasica (gitar) ve Jen Ledger (davul, vokal). Ledger 18 yaşında İngiltere'den gelerek gruba katıldı.",
    members: ["John Cooper – vokal, bas", "Korey Cooper – ritim gitar, klavye", "Ben Kasica – solo gitar", "Jen Ledger – davul, vokal"],
    funFacts: [
      "\"Monster\" WWE, NFL ve sayısız spor programında kullanıldı.",
      "Jen Ledger davul çalarken vokal yapan nadir davulculardan biri.",
      "Albüm, Skillet'ın Billboard 200'de Top 5'e giren ilk kaydı oldu.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "badflower-ok-im-sick",
    artist: "Badflower",
    title: "OK, I'm Sick",
    year: 2019,
    deezerId: 87718482,
    genres: ["Alternatif rock", "Hard rock", "Grunge"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "\"Ghost\" ve \"Heroin\" — Three Days Grace'in dürüstlüğünü yeni kuşakta arıyorsan.",
    story: [
      "Los Angeles'lı dörtlü, Taylor Swift'i keşfeden Big Machine'in rock etiketiyle anlaştı. Çıkış albümü, Josh Katz'ın intihar düşünceleri, panik atakları ve bağımlılıkla ilgili sözleriyle radyoların çalmakta tereddüt ettiği ama sonunda 1 numaraya çıkan \"Ghost\" ile açıldı.",
      "\"Heroin\", \"The Jester\", \"Promise Me\" ve \"x ANA x\" ile albüm, 2010'ların sonunda rock'ın ham ve itiraf niteliğindeki yüzünü temsil etti. Katz'ın sahnede kontrolden çıkmış performansları grubun canlı ününü kurdu.",
    ],
    artistInfo:
      "Badflower: Josh Katz (vokal, gitar), Joey Morrow (gitar), Alex Espiritu (bas) ve Anthony Sonetti (davul). Grup 2013'te Los Angeles'ta kuruldu.",
    members: ["Josh Katz – vokal, gitar", "Joey Morrow – solo gitar", "Alex Espiritu – bas", "Anthony Sonetti – davul"],
    funFacts: [
      "\"Ghost\" grubun ilk 1 numarası oldu ve intihar konusunu rock radyosunda açıkça tartışmaya açtı.",
      "Grup, Scott Borchetta'nın Big Machine etiketinin ilk rock imzalarından biri.",
      "Katz'ın panik ataklarını anlatan \"x ANA x\", albümün en kişisel şarkısı.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin"],
  },
  {
    slug: "thirty-seconds-to-mars-a-beautiful-lie",
    artist: "Thirty Seconds to Mars",
    title: "A Beautiful Lie",
    year: 2005,
    deezerId: 299307,
    genres: ["Alternatif rock", "Emo", "Uzay rock"],
    origin: "Los Angeles, Kaliforniya, ABD",
    why: "\"The Kill\" ve \"From Yesterday\" — Breaking Benjamin sevenlerin sıklıkla yanına koyduğu albüm.",
    story: [
      "Jared Leto'nun film takvimi nedeniyle albüm dört kıtada, üç yıla yayılan seanslarla kaydedildi — bazı bölümler Leto'nun Lord of War'u çektiği Cape Town'da yapıldı. Kayıtlar tamamlanmadan internete sızdı; grup buna karşılık bonus şarkılar ekledi.",
      "\"The Kill (Bury Me)\", Modern Rock listesinde 52 hafta kalarak bir rekor kırdı; klibi The Shining'e gönderme yapıyor. \"From Yesterday\" klibi Çin'de çekilen ilk Amerikan rock klibi oldu. Albüm platin sertifika aldı.",
    ],
    artistInfo:
      "Thirty Seconds to Mars: Jared Leto (vokal, gitar), Shannon Leto (davul), Tomo Miličević (gitar) ve Matt Wachter (bas). Kardeşler Leto grubu 1998'de kurdu; grubun hayran topluluğu 'Echelon' olarak bilinir.",
    members: ["Jared Leto – vokal, gitar", "Shannon Leto – davul", "Tomo Miličević – gitar", "Matt Wachter – bas"],
    funFacts: [
      "\"The Kill\" klibi Stanley Kubrick'in The Shining filminin bir yeniden yorumu.",
      "\"A Beautiful Lie\" klibi Grönland'da iklim değişikliğine dikkat çekmek için çekildi.",
      "Albüm çıkmadan önce sızdırıldığı için grup son anda yeni parçalar ekledi.",
    ],
    relatedTo: ["Breaking Benjamin", "Panic! At the Disco"],
  },
  {
    slug: "nirvana-nevermind",
    artist: "Nirvana",
    title: "Nevermind",
    year: 1991,
    deezerId: 1252978,
    genres: ["Grunge", "Alternatif rock"],
    origin: "Aberdeen, Washington, ABD",
    why: "Three Days Grace, Breaking Benjamin, Seether — hepsinin ortak atası. Post-grunge'ın 'grunge'ı.",
    story: [
      "Butch Vig prodüktörlüğünde Los Angeles'taki Sound City'de kaydedilen Nevermind için Geffen 250.000 satış bekliyordu. Ocak 1992'de albüm Michael Jackson'ın Dangerous'ını tahtından indirip Billboard 200'de 1 numaraya çıktı ve alternatif rock'ı bir gecede ana akım yaptı.",
      "\"Smells Like Teen Spirit\"in adı, Kathleen Hanna'nın Cobain'in duvarına yazdığı 'Kurt smells like Teen Spirit' grafitisinden geliyor — Cobain bunun bir deodorant markası olduğunu bilmiyordu. Kapaktaki bebek Spencer Elden, bir dolar peşinde yüzüyor. Albüm 30 milyondan fazla sattı.",
    ],
    artistInfo:
      "Nirvana: Kurt Cobain (vokal, gitar), Krist Novoselic (bas) ve 1990'da katılan Dave Grohl (davul). Nevermind, üçlünün bu kadroyla yaptığı ilk albüm.",
    members: ["Kurt Cobain – vokal, gitar", "Krist Novoselic – bas", "Dave Grohl – davul, geri vokal"],
    funFacts: [
      "Albümün sonundaki gizli parça \"Endless, Nameless\" yaklaşık 10 dakikalık sessizliğin ardından başlar; ilk baskılarda yanlışlıkla yer almadı.",
      "Kapak fikrinin çıkış noktası, Cobain'in televizyonda izlediği bir su doğumu belgeseliydi.",
      "Geffen albümden 250.000 satış bekliyordu; Nevermind zirvedeyken haftada 300.000 satıyordu.",
    ],
    relatedTo: ["Three Days Grace", "Breaking Benjamin", "Foo Fighters"],
  },
];
